/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manager;

import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import manager.util.SQLColumn;

/**
 *
 * @author user
 */
public class CrimeDiaryDialog extends javax.swing.JDialog {

    /**
     * Creates new form CrimeDiaryDialog
     */
    public CrimeDiaryDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.addWindowListener(new WindowAdapter() {

            @Override
            public void windowOpened(WindowEvent e) {
                Object[] obj_states = ServerManager.mapStatesAndLGAs.keySet().toArray();
                Arrays.sort(obj_states);
                
                if (cboCrimeDiaryState.getItemCount() != obj_states.length) {
                    cboCrimeDiaryState.removeAllItems();//clear previous
                    for (Object obj_state : obj_states) {
                        cboCrimeDiaryState.addItem(obj_state);
                    }
                }
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel190 = new javax.swing.JLabel();
        jLabel191 = new javax.swing.JLabel();
        lblCrimeDiaryFirstName = new javax.swing.JLabel();
        lblCrimeDiarySurname = new javax.swing.JLabel();
        jLabel194 = new javax.swing.JLabel();
        lblCrimeDiarySex = new javax.swing.JLabel();
        jLabel196 = new javax.swing.JLabel();
        lblCrimeDiaryAge = new javax.swing.JLabel();
        txtCrimeDiarySearch = new javax.swing.JTextField();
        cmdCrimeDiarySearch = new javax.swing.JButton();
        jLabel198 = new javax.swing.JLabel();
        imgCrimeDiaryPhoto = new org.jdesktop.swingx.JXImageView();
        jLabel199 = new javax.swing.JLabel();
        lblCrimeDiaryDateOfArrest = new javax.swing.JLabel();
        jLabel201 = new javax.swing.JLabel();
        cboCrimeDiaryCaseStatus = new javax.swing.JComboBox();
        cmdCrimeDiaryUpdate = new javax.swing.JButton();
        cmdCrimeDiaryClose = new javax.swing.JButton();
        cboCrimeDiaryState = new javax.swing.JComboBox();
        cboCrimeDiaryLGA = new javax.swing.JComboBox();
        jSeparator25 = new javax.swing.JSeparator();
        jLabel192 = new javax.swing.JLabel();
        jLabel193 = new javax.swing.JLabel();
        jScrollPane19 = new javax.swing.JScrollPane();
        lstCrimeDiarySearchList = new javax.swing.JList();
        jLabel195 = new javax.swing.JLabel();
        jLabel197 = new javax.swing.JLabel();
        dpCrimeDiaryStatusDate = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crime Diary");
        setBounds(this.getCenteredBounds(0.8, 0.95));
        setPreferredSize(this.getFormDimension(0.8, 0.95));

        jLabel190.setText("First name");

        jLabel191.setText("Surname");

        jLabel194.setText("Sex");

        jLabel196.setText("Age");

        cmdCrimeDiarySearch.setText("Search");
        cmdCrimeDiarySearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrimeDiarySearchActionPerformed(evt);
            }
        });

        jLabel198.setText("Enter name of the arrested person");

        javax.swing.GroupLayout imgCrimeDiaryPhotoLayout = new javax.swing.GroupLayout(imgCrimeDiaryPhoto);
        imgCrimeDiaryPhoto.setLayout(imgCrimeDiaryPhotoLayout);
        imgCrimeDiaryPhotoLayout.setHorizontalGroup(
            imgCrimeDiaryPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );
        imgCrimeDiaryPhotoLayout.setVerticalGroup(
            imgCrimeDiaryPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );

        jLabel199.setText("Date of arrest");

        jLabel201.setText("Case status");

        cboCrimeDiaryCaseStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Released on bail", "Charged to court", "In detention", "Executed", "Case settled" }));
        cboCrimeDiaryCaseStatus.setEnabled(false);

        cmdCrimeDiaryUpdate.setText("Edit");
        cmdCrimeDiaryUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrimeDiaryUpdateActionPerformed(evt);
            }
        });

        cmdCrimeDiaryClose.setText("Close");
        cmdCrimeDiaryClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrimeDiaryCloseActionPerformed(evt);
            }
        });

        cboCrimeDiaryState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCrimeDiaryStateActionPerformed(evt);
            }
        });

        jLabel192.setText("State");

        jLabel193.setText("LGA");

        lstCrimeDiarySearchList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstCrimeDiarySearchList.setToolTipText("");
        lstCrimeDiarySearchList.setFixedCellHeight(30);
        lstCrimeDiarySearchList.setPreferredSize(new java.awt.Dimension(240, 150));
        lstCrimeDiarySearchList.setSelectionBackground(new java.awt.Color(0, 153, 153));
        lstCrimeDiarySearchList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCrimeDiarySearchListValueChanged(evt);
            }
        });
        jScrollPane19.setViewportView(lstCrimeDiarySearchList);

        jLabel195.setText("Matching Results");

        jLabel197.setText("Status date");

        dpCrimeDiaryStatusDate.setEnabled(false);
        dpCrimeDiaryStatusDate.setFormats(new SimpleDateFormat("yyyy-MM-dd"));
        dpCrimeDiaryStatusDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpCrimeDiaryStatusDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel198, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCrimeDiarySearch, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel192, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboCrimeDiaryState, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboCrimeDiaryLGA, 0, 140, Short.MAX_VALUE)
                            .addComponent(jLabel193, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(57, 57, 57)
                        .addComponent(cmdCrimeDiarySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator25)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel197, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(dpCrimeDiaryStatusDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel201, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel190, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel191, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel199, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel196, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel194, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblCrimeDiarySurname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblCrimeDiaryFirstName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(lblCrimeDiarySex, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(lblCrimeDiaryAge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblCrimeDiaryDateOfArrest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(cboCrimeDiaryCaseStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(cmdCrimeDiaryClose, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(imgCrimeDiaryPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(cmdCrimeDiaryUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel195, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(17, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel198)
                    .addComponent(jLabel192)
                    .addComponent(jLabel193))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCrimeDiarySearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboCrimeDiaryState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboCrimeDiaryLGA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdCrimeDiarySearch))
                .addGap(18, 18, 18)
                .addComponent(jSeparator25, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel195)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel190)
                                    .addComponent(lblCrimeDiaryFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel191)
                                    .addComponent(lblCrimeDiarySurname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel194)
                                    .addComponent(lblCrimeDiarySex, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel196)
                                    .addComponent(lblCrimeDiaryAge, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel199)
                                    .addComponent(lblCrimeDiaryDateOfArrest, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(imgCrimeDiaryPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel201)
                            .addComponent(cboCrimeDiaryCaseStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel197)
                            .addComponent(dpCrimeDiaryStatusDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdCrimeDiaryUpdate))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdCrimeDiaryClose)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCrimeDiarySearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrimeDiarySearchActionPerformed

        String search_name = this.txtCrimeDiarySearch.getText();
        if (search_name.isEmpty()) {
            return;
        }

        String s = "";
        while (!s.equals(search_name)) {
            search_name = search_name.replaceAll("  ", " ");
            s = search_name.replaceAll("  ", " ");
        }

        String[] name = search_name.trim().split(" ");
        String first_name = name[0];
        String surname = name[1];
        String _state = this.cboCrimeDiaryState.getSelectedItem().toString();
        String _lga = this.cboCrimeDiaryLGA.getSelectedItem().toString();

        DBResource dBResource = null;

        try {

            String columns[] = new String[]{"SN",
                "FIRST_NAME",
                "SURNAME",
                "SEX",
                "DATE_OF_BIRTH",
                "PHONE_NO",
                "REASON_FOR_ARREST",
                "DATE_OF_ARREST",
                "CASE_STATUS",
                "STATUS_DATE",
                "PHOTO_FILE_NAME"};

            String condition = " WHERE FIRST_NAME='" + first_name + "'"
                    + "AND SURNAME='" + surname + "'"
                    + "AND STATE='" + _state + "'"
                    + "AND LGA='" + _lga + "'";

            dBResource = ServerManager.sendQueryAutoPolice("crime_case", columns, condition);
            this.lstCrimeDiarySearchList.setListData(new Vector());//first clear
            Vector v = new Vector();
            ServerManager.crime_person = new HashMap();
            int index = -1;//used for track the position on the list of names
            while (dBResource.rs.next()) {
                String fname = dBResource.rs.getString("FIRST_NAME");
                String lname = dBResource.rs.getString("SURNAME");
                String full_name = fname + " " + lname;
                v.add(full_name);
                Person person = new Person();
                person.serial_no = dBResource.rs.getInt("SN");;
                person.first_name = fname;
                person.last_name = lname;
                person.age = dBResource.rs.getString("DATE_OF_BIRTH");
                person.sex = dBResource.rs.getString("SEX");
                person.phone_no = dBResource.rs.getString("PHONE_NO");
                person.reason_for_arrest = dBResource.rs.getString("REASON_FOR_ARREST");
                person.date_of_arrest = dBResource.rs.getString("DATE_OF_ARREST");
                person.photo_file_name = dBResource.rs.getString("PHOTO_FILE_NAME");
                person.case_status = dBResource.rs.getString("CASE_STATUS");
                person.status_date = dBResource.rs.getString("STATUS_DATE");
                index++;
                ServerManager.crime_person.put(index, person);

                ServerManager.imageLoader.loadImage(person.photo_file_name, this.imgCrimeDiaryPhoto);//load the image
            }

            this.lstCrimeDiarySearchList.setListData(v);

        } catch (SQLException ex) {
            Logger.getLogger(ServerManager.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            if (dBResource != null) {
                dBResource.close();
            }
        }
    }//GEN-LAST:event_cmdCrimeDiarySearchActionPerformed

    private void cmdCrimeDiaryUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrimeDiaryUpdateActionPerformed

        if (!this.cboCrimeDiaryCaseStatus.isEnabled()) {
            this.cmdCrimeDiaryUpdate.setText("Update");
            this.cboCrimeDiaryCaseStatus.setEnabled(true);
            this.dpCrimeDiaryStatusDate.setEnabled(true);
            return;
        }

        DBResource dBResource = null;
        Object case_status = this.cboCrimeDiaryCaseStatus.getSelectedItem();
        if (case_status == null) {
            JOptionPane.showMessageDialog(this, "Case status not selected!", "Invalid", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String status_date = this.dpCrimeDiaryStatusDate.getEditor().getText();
        if (status_date.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Case status date is emtpy!", "Invalid", JOptionPane.ERROR_MESSAGE);
            return;
        }

        SQLColumn[] sql_columns = {new SQLColumn("CASE_STATUS", case_status.toString()),
            new SQLColumn("STATUS_DATE", status_date)};

        int index = this.lstCrimeDiarySearchList.getSelectedIndex();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "No person selected!", "Invalid", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Person person = ServerManager.crime_person.get(index);
        String condition = "WHERE SN=" + person.serial_no;

        try {
            dBResource = ServerManager.updateStatementAutoPolice("crime_case", sql_columns, condition, true);
            this.cmdCrimeDiaryUpdate.setText("Edit");
            this.cboCrimeDiaryCaseStatus.setEnabled(false);
            this.dpCrimeDiaryStatusDate.setEnabled(false);
        } catch (Exception ex) {
            ex.printStackTrace();
        } finally {
            dBResource.close();
        }
    }//GEN-LAST:event_cmdCrimeDiaryUpdateActionPerformed

    private void cmdCrimeDiaryCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrimeDiaryCloseActionPerformed
        //this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_cmdCrimeDiaryCloseActionPerformed

    private void cboCrimeDiaryStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCrimeDiaryStateActionPerformed

        Object o_state = this.cboCrimeDiaryState.getSelectedItem();

        ArrayList lgas_list = ServerManager.mapStatesAndLGAs.get((String) o_state);

        this.cboCrimeDiaryLGA.removeAllItems();
        Object[] lgas = lgas_list.toArray();
        Arrays.sort(lgas);
        for (Object lga : lgas) {
            this.cboCrimeDiaryLGA.addItem(lga);
        }

    }//GEN-LAST:event_cboCrimeDiaryStateActionPerformed

    private void lstCrimeDiarySearchListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCrimeDiarySearchListValueChanged

        Person person = ServerManager.crime_person.get(evt.getFirstIndex());
        if (person == null) {
            return;
        }
        this.lblCrimeDiaryFirstName.setText(person.first_name);
        this.lblCrimeDiarySurname.setText(person.last_name);
        this.lblCrimeDiaryAge.setText(person.age);
        this.lblCrimeDiarySex.setText(person.sex);
        this.lblCrimeDiaryDateOfArrest.setText(person.date_of_arrest);
        this.cboCrimeDiaryCaseStatus.setSelectedItem(person.case_status);
        this.dpCrimeDiaryStatusDate.getEditor().setText(person.status_date);

        ServerManager.imageLoader.loadImage(person.photo_file_name, imgCrimeDiaryPhoto);
    }//GEN-LAST:event_lstCrimeDiarySearchListValueChanged

    private void dpCrimeDiaryStatusDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpCrimeDiaryStatusDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpCrimeDiaryStatusDateActionPerformed

    Rectangle getCenteredBounds(double percent_screen_width, double percent_screen_height) {
        int task_bar_height = 37;
        int screen_width = (int) this.getGraphicsConfiguration().getBounds().getWidth();
        int screen_height = (int) this.getGraphicsConfiguration().getBounds().getHeight();
        int w = (int) (percent_screen_width * screen_width);
        int h = (int) (percent_screen_height * screen_height);

        int x = (int) ((screen_width - w) / 2);
        int y = (int) ((screen_height - h) / 2);

        if (h + y > screen_height - task_bar_height) {
            y = 0;
            h = screen_height - task_bar_height;
        }
        return new Rectangle(x, y, w, h);
    }

    private Dimension getFormDimension(double percent_screen_width, double percent_screen_height) {

        int screen_width = (int) this.getGraphicsConfiguration().getBounds().getWidth();
        int screen_height = (int) this.getGraphicsConfiguration().getBounds().getHeight();
        int w = (int) (percent_screen_width * screen_width);
        int h = (int) (percent_screen_height * screen_height);

        return new Dimension(w, h);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrimeDiaryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrimeDiaryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrimeDiaryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrimeDiaryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CrimeDiaryDialog dialog = new CrimeDiaryDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboCrimeDiaryCaseStatus;
    private javax.swing.JComboBox cboCrimeDiaryLGA;
    private javax.swing.JComboBox cboCrimeDiaryState;
    private javax.swing.JButton cmdCrimeDiaryClose;
    private javax.swing.JButton cmdCrimeDiarySearch;
    private javax.swing.JButton cmdCrimeDiaryUpdate;
    private org.jdesktop.swingx.JXDatePicker dpCrimeDiaryStatusDate;
    private org.jdesktop.swingx.JXImageView imgCrimeDiaryPhoto;
    private javax.swing.JLabel jLabel190;
    private javax.swing.JLabel jLabel191;
    private javax.swing.JLabel jLabel192;
    private javax.swing.JLabel jLabel193;
    private javax.swing.JLabel jLabel194;
    private javax.swing.JLabel jLabel195;
    private javax.swing.JLabel jLabel196;
    private javax.swing.JLabel jLabel197;
    private javax.swing.JLabel jLabel198;
    private javax.swing.JLabel jLabel199;
    private javax.swing.JLabel jLabel201;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JLabel lblCrimeDiaryAge;
    private javax.swing.JLabel lblCrimeDiaryDateOfArrest;
    private javax.swing.JLabel lblCrimeDiaryFirstName;
    private javax.swing.JLabel lblCrimeDiarySex;
    private javax.swing.JLabel lblCrimeDiarySurname;
    private javax.swing.JList lstCrimeDiarySearchList;
    private javax.swing.JTextField txtCrimeDiarySearch;
    // End of variables declaration//GEN-END:variables
}
