/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manager;

import java.awt.Dimension;
import java.awt.Rectangle;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import manager.util.SQLColumn;

/**
 *
 * @author user
 */
public class CrimeControlDialog extends javax.swing.JDialog {

    /**
     * Creates new form CrimeControlDialog
     */
    public CrimeControlDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPreciousCaseIndicator = new javax.swing.JPanel();
        lblPreviousCaseIndicator = new javax.swing.JLabel();
        cmdCrimeControlRelatedCase = new javax.swing.JButton();
        ScrollPaneCrimeControl = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        pnlPreviousCaseInfo = new javax.swing.JPanel();
        lblPreviousCaseSex = new javax.swing.JLabel();
        jLabel203 = new javax.swing.JLabel();
        jLabel204 = new javax.swing.JLabel();
        lblPreviousCaseAge = new javax.swing.JLabel();
        jLabel205 = new javax.swing.JLabel();
        lblPreviousCaseDateOfArrest = new javax.swing.JLabel();
        imgPreviousCasePhoto = new org.jdesktop.swingx.JXImageView();
        jLabel206 = new javax.swing.JLabel();
        jLabel207 = new javax.swing.JLabel();
        lblPreviousCaseSurname = new javax.swing.JLabel();
        jLabel208 = new javax.swing.JLabel();
        jLabel209 = new javax.swing.JLabel();
        lblPreviousCaseFirstName = new javax.swing.JLabel();
        jLabel210 = new javax.swing.JLabel();
        jScrollPane20 = new javax.swing.JScrollPane();
        lstPreviousCaseSearchList = new javax.swing.JList();
        lblPreviousCaseStatus = new javax.swing.JLabel();
        lblPreviousCaseStatusDate = new javax.swing.JLabel();
        jLabel211 = new javax.swing.JLabel();
        jLabel212 = new javax.swing.JLabel();
        jLabel213 = new javax.swing.JLabel();
        lblPreviousCaseState = new javax.swing.JLabel();
        lblPreviousCaseLGA = new javax.swing.JLabel();
        lblPreviousCaseStation = new javax.swing.JLabel();
        jLabel214 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblPreviousCaseReasonForArrest = new javax.swing.JTextArea();
        pnlCrimeControlCase = new javax.swing.JPanel();
        cboCrimeControlStatus = new javax.swing.JComboBox();
        imgCrimeControlPhoto = new org.jdesktop.swingx.JXImageView();
        jLabel200 = new javax.swing.JLabel();
        txtCrimeControlSave = new javax.swing.JButton();
        jLabel168 = new javax.swing.JLabel();
        txtCrimeControlCancel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCrimeControlReasonOfArrest = new javax.swing.JTextArea();
        jLabel170 = new javax.swing.JLabel();
        txtCrimeControlFirtName = new javax.swing.JTextField();
        txtCrimeControlPhoneNo = new javax.swing.JTextField();
        jLabel188 = new javax.swing.JLabel();
        txtCrimeControlSurname = new javax.swing.JTextField();
        jLabel189 = new javax.swing.JLabel();
        jLabel172 = new javax.swing.JLabel();
        txtCrimeControlDateArrested = new org.jdesktop.swingx.JXDatePicker();
        jLabel173 = new javax.swing.JLabel();
        txtCrimeControlBrowsePhoto = new javax.swing.JButton();
        txtCrimeControlDateOfBirth = new org.jdesktop.swingx.JXDatePicker();
        jLabel171 = new javax.swing.JLabel();
        txtCrimeControlSex = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crime Control");
        setBounds(this.getCenteredBounds(0.8, 0.9));
        setPreferredSize(this.getFormDimension(0.8, 0.9));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        pnlPreciousCaseIndicator.setMaximumSize(new java.awt.Dimension(32767, 0));
        pnlPreciousCaseIndicator.setPreferredSize(new java.awt.Dimension(706, 80));

        lblPreviousCaseIndicator.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPreviousCaseIndicator.setForeground(new java.awt.Color(255, 51, 51));
        lblPreviousCaseIndicator.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPreviousCaseIndicator.setText("Found 100 cases relating to Jude Okemni");

        cmdCrimeControlRelatedCase.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmdCrimeControlRelatedCase.setForeground(new java.awt.Color(255, 51, 51));
        cmdCrimeControlRelatedCase.setText("View cases");
        cmdCrimeControlRelatedCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrimeControlRelatedCaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPreciousCaseIndicatorLayout = new javax.swing.GroupLayout(pnlPreciousCaseIndicator);
        pnlPreciousCaseIndicator.setLayout(pnlPreciousCaseIndicatorLayout);
        pnlPreciousCaseIndicatorLayout.setHorizontalGroup(
            pnlPreciousCaseIndicatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
            .addGroup(pnlPreciousCaseIndicatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlPreciousCaseIndicatorLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblPreviousCaseIndicator, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cmdCrimeControlRelatedCase, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        pnlPreciousCaseIndicatorLayout.setVerticalGroup(
            pnlPreciousCaseIndicatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
            .addGroup(pnlPreciousCaseIndicatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlPreciousCaseIndicatorLayout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addGroup(pnlPreciousCaseIndicatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPreviousCaseIndicator)
                        .addComponent(cmdCrimeControlRelatedCase))
                    .addContainerGap(18, Short.MAX_VALUE)))
        );

        getContentPane().add(pnlPreciousCaseIndicator);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.PAGE_AXIS));

        pnlPreviousCaseInfo.setBackground(new java.awt.Color(153, 153, 153));
        pnlPreviousCaseInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Previous Cases"));
        pnlPreviousCaseInfo.setMaximumSize(new java.awt.Dimension(32767, 0));
        pnlPreviousCaseInfo.setPreferredSize(new java.awt.Dimension(706, 0));

        jLabel203.setText("Sex");

        jLabel204.setText("Age");

        jLabel205.setText("Date of arrest");

        javax.swing.GroupLayout imgPreviousCasePhotoLayout = new javax.swing.GroupLayout(imgPreviousCasePhoto);
        imgPreviousCasePhoto.setLayout(imgPreviousCasePhotoLayout);
        imgPreviousCasePhotoLayout.setHorizontalGroup(
            imgPreviousCasePhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );
        imgPreviousCasePhotoLayout.setVerticalGroup(
            imgPreviousCasePhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );

        jLabel206.setText("Case status");

        jLabel207.setText("Status date");

        jLabel208.setText("First name");

        jLabel209.setText("Surname");

        jLabel210.setText("Matching Results");

        lstPreviousCaseSearchList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstPreviousCaseSearchList.setToolTipText("");
        lstPreviousCaseSearchList.setFixedCellHeight(30);
        lstPreviousCaseSearchList.setPreferredSize(new java.awt.Dimension(240, 150));
        lstPreviousCaseSearchList.setSelectionBackground(new java.awt.Color(0, 153, 153));
        lstPreviousCaseSearchList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPreviousCaseSearchListValueChanged(evt);
            }
        });
        jScrollPane20.setViewportView(lstPreviousCaseSearchList);

        jLabel211.setText("State");

        jLabel212.setText("LGA");

        jLabel213.setText("Station");

        jLabel214.setText("Reason for arrest");

        lblPreviousCaseReasonForArrest.setEditable(false);
        lblPreviousCaseReasonForArrest.setColumns(20);
        lblPreviousCaseReasonForArrest.setRows(5);
        jScrollPane1.setViewportView(lblPreviousCaseReasonForArrest);

        javax.swing.GroupLayout pnlPreviousCaseInfoLayout = new javax.swing.GroupLayout(pnlPreviousCaseInfo);
        pnlPreviousCaseInfo.setLayout(pnlPreviousCaseInfoLayout);
        pnlPreviousCaseInfoLayout.setHorizontalGroup(
            pnlPreviousCaseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPreviousCaseInfoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnlPreviousCaseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPreviousCaseInfoLayout.createSequentialGroup()
                        .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(pnlPreviousCaseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPreviousCaseInfoLayout.createSequentialGroup()
                                .addGroup(pnlPreviousCaseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel209, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel213, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel203, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel204, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel206, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel205, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel214, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel207, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel212, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel208, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlPreviousCaseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlPreviousCaseInfoLayout.createSequentialGroup()
                                        .addGroup(pnlPreviousCaseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblPreviousCaseState, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                            .addComponent(lblPreviousCaseFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblPreviousCaseSurname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblPreviousCaseSex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblPreviousCaseAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblPreviousCaseDateOfArrest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblPreviousCaseStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                            .addComponent(lblPreviousCaseLGA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                            .addComponent(lblPreviousCaseStation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(imgPreviousCasePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(pnlPreviousCaseInfoLayout.createSequentialGroup()
                                        .addGroup(pnlPreviousCaseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPreviousCaseStatusDate, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(pnlPreviousCaseInfoLayout.createSequentialGroup()
                                .addComponent(jLabel211, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(pnlPreviousCaseInfoLayout.createSequentialGroup()
                        .addComponent(jLabel210, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        pnlPreviousCaseInfoLayout.setVerticalGroup(
            pnlPreviousCaseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPreviousCaseInfoLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel210)
                .addGap(6, 6, 6)
                .addGroup(pnlPreviousCaseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPreviousCaseInfoLayout.createSequentialGroup()
                        .addGroup(pnlPreviousCaseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPreviousCaseInfoLayout.createSequentialGroup()
                                .addComponent(jLabel208)
                                .addGap(17, 17, 17)
                                .addComponent(jLabel209)
                                .addGap(17, 17, 17)
                                .addComponent(jLabel203)
                                .addGap(17, 17, 17)
                                .addComponent(jLabel204)
                                .addGap(17, 17, 17)
                                .addComponent(jLabel205)
                                .addGap(17, 17, 17)
                                .addGroup(pnlPreviousCaseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel206)
                                    .addComponent(lblPreviousCaseStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlPreviousCaseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(imgPreviousCasePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPreviousCaseInfoLayout.createSequentialGroup()
                                    .addComponent(lblPreviousCaseFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(11, 11, 11)
                                    .addComponent(lblPreviousCaseSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(11, 11, 11)
                                    .addComponent(lblPreviousCaseSex, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(11, 11, 11)
                                    .addComponent(lblPreviousCaseAge, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(11, 11, 11)
                                    .addComponent(lblPreviousCaseDateOfArrest, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPreviousCaseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel214))
                        .addGap(18, 18, 18)
                        .addGroup(pnlPreviousCaseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPreviousCaseStatusDate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel207))
                        .addGap(17, 17, 17)
                        .addGroup(pnlPreviousCaseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel211)
                            .addComponent(lblPreviousCaseState, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(pnlPreviousCaseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPreviousCaseLGA, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel212, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(pnlPreviousCaseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel213)
                            .addComponent(lblPreviousCaseStation, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.add(pnlPreviousCaseInfo);

        pnlCrimeControlCase.setPreferredSize(new java.awt.Dimension(554, 400));

        cboCrimeControlStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ARRESTED", "WANTED" }));
        cboCrimeControlStatus.setSelectedIndex(-1);

        javax.swing.GroupLayout imgCrimeControlPhotoLayout = new javax.swing.GroupLayout(imgCrimeControlPhoto);
        imgCrimeControlPhoto.setLayout(imgCrimeControlPhotoLayout);
        imgCrimeControlPhotoLayout.setHorizontalGroup(
            imgCrimeControlPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
        );
        imgCrimeControlPhotoLayout.setVerticalGroup(
            imgCrimeControlPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );

        jLabel200.setText("Status");

        txtCrimeControlSave.setText("Save");
        txtCrimeControlSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCrimeControlSaveActionPerformed(evt);
            }
        });

        jLabel168.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel168.setText("First name");

        txtCrimeControlCancel.setText("Cancel");
        txtCrimeControlCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCrimeControlCancelActionPerformed(evt);
            }
        });

        txtCrimeControlReasonOfArrest.setColumns(20);
        txtCrimeControlReasonOfArrest.setRows(5);
        jScrollPane2.setViewportView(txtCrimeControlReasonOfArrest);

        jLabel170.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel170.setText("Surname");

        txtCrimeControlFirtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCrimeControlFirtNametxtCrimeControlNameFocusLost(evt);
            }
        });

        jLabel188.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel188.setText("Reason for arrest");

        txtCrimeControlSurname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCrimeControlSurnametxtCrimeControlNameFocusLost(evt);
            }
        });

        jLabel189.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel189.setText("Date arrested");

        jLabel172.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel172.setText("Date of birth");

        txtCrimeControlDateArrested.setDate(getDefaultDate());
        txtCrimeControlDateArrested.setFormats(new SimpleDateFormat("yyyy-MM-dd"));
        txtCrimeControlDateArrested.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCrimeControlDateArrestedActionPerformed(evt);
            }
        });

        jLabel173.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel173.setText("Phone no.");

        txtCrimeControlBrowsePhoto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCrimeControlBrowsePhoto.setText("Browse photo");
        txtCrimeControlBrowsePhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCrimeControlBrowsePhotoActionPerformed(evt);
            }
        });

        txtCrimeControlDateOfBirth.setDate(getDefaultDate());
        txtCrimeControlDateOfBirth.setFormats(new SimpleDateFormat("yyyy-MM-dd"));

        jLabel171.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel171.setText("Sex");

        txtCrimeControlSex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        txtCrimeControlSex.setSelectedIndex(-1);

        javax.swing.GroupLayout pnlCrimeControlCaseLayout = new javax.swing.GroupLayout(pnlCrimeControlCase);
        pnlCrimeControlCase.setLayout(pnlCrimeControlCaseLayout);
        pnlCrimeControlCaseLayout.setHorizontalGroup(
            pnlCrimeControlCaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCrimeControlCaseLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(pnlCrimeControlCaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCrimeControlCaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel188, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel173, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel172, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel171, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel170, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel168, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel189, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel200))
                .addGap(18, 18, 18)
                .addGroup(pnlCrimeControlCaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlCrimeControlCaseLayout.createSequentialGroup()
                        .addComponent(txtCrimeControlSave, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCrimeControlCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(cboCrimeControlStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCrimeControlFirtName)
                    .addComponent(txtCrimeControlSurname)
                    .addComponent(txtCrimeControlPhoneNo)
                    .addComponent(txtCrimeControlDateOfBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCrimeControlDateArrested, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(txtCrimeControlSex, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addGroup(pnlCrimeControlCaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCrimeControlBrowsePhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imgCrimeControlPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        pnlCrimeControlCaseLayout.setVerticalGroup(
            pnlCrimeControlCaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCrimeControlCaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCrimeControlCaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCrimeControlCaseLayout.createSequentialGroup()
                        .addGroup(pnlCrimeControlCaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel168)
                            .addComponent(txtCrimeControlFirtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlCrimeControlCaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel170)
                            .addComponent(txtCrimeControlSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlCrimeControlCaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel171)
                            .addComponent(txtCrimeControlSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlCrimeControlCaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel172)
                            .addComponent(txtCrimeControlDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlCrimeControlCaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel173)
                            .addComponent(txtCrimeControlPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(imgCrimeControlPhoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCrimeControlCaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCrimeControlBrowsePhoto)
                    .addComponent(jLabel200)
                    .addComponent(cboCrimeControlStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCrimeControlCaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel188)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCrimeControlCaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCrimeControlDateArrested, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel189))
                .addGap(31, 31, 31)
                .addGroup(pnlCrimeControlCaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCrimeControlSave)
                    .addComponent(txtCrimeControlCancel))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jPanel6.add(pnlCrimeControlCase);

        ScrollPaneCrimeControl.setViewportView(jPanel6);

        getContentPane().add(ScrollPaneCrimeControl);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCrimeControlRelatedCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrimeControlRelatedCaseActionPerformed
        //this.pnlPreviousCaseInfo.setVisible(false);
        pnlPreviousCaseInfo.setPreferredSize(new Dimension(pnlPreviousCaseInfo.getWidth(), 0));
        final int _height = 400;
        final int duration = 2000 / 400;

        new Thread(new Runnable() {
            public void run() {
                for (int i = 1; i < _height + 1; i++) {
                    final int h = i;
                    SwingUtilities.invokeLater(new Runnable() {
                        public void run() {
                            int w = pnlPreviousCaseInfo.getWidth();
                            pnlPreviousCaseInfo.setPreferredSize(new Dimension(w, h));
                            pnlPreviousCaseInfo.revalidate();
                        }
                    });

                    try {
                        Thread.sleep(duration);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(ServerManager.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }//GEN-LAST:event_cmdCrimeControlRelatedCaseActionPerformed

    private void lstPreviousCaseSearchListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPreviousCaseSearchListValueChanged

        System.out.println(evt.getFirstIndex());
        Person person = ServerManager.crime_person.get(evt.getFirstIndex());
        if (person == null) {
            return;
        }

        this.lblPreviousCaseFirstName.setText(person.first_name);
        this.lblPreviousCaseSurname.setText(person.last_name);
        this.lblPreviousCaseAge.setText(person.age);
        this.lblPreviousCaseSex.setText(person.sex);
        this.lblPreviousCaseDateOfArrest.setText(person.date_of_arrest);
        this.lblPreviousCaseStatus.setText(person.case_status);
        this.lblPreviousCaseReasonForArrest.setText(person.reason_for_arrest);
        this.lblPreviousCaseState.setText(person.state);
        this.lblPreviousCaseLGA.setText(person.lga);
        this.lblPreviousCaseStation.setText(person.station);
        this.lblPreviousCaseStatusDate.setText(person.status_date);

        ServerManager.imageLoader.loadImage(person.photo_file_name, imgPreviousCasePhoto);

    }//GEN-LAST:event_lstPreviousCaseSearchListValueChanged

    private void txtCrimeControlSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCrimeControlSaveActionPerformed

        Object status = this.cboCrimeControlStatus.getSelectedItem();

        if (status == null) {
            JOptionPane.showMessageDialog(this, "Status not selected!", "Invalid", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (status.toString().equals("ARRESTED")) {

            JComponent[] except_fields = {};//no exceptions
            if (!ServerManager.validateEmptyInput(this, except_fields)) {
                JOptionPane.showMessageDialog(this, "Field is empty", "Invalid", JOptionPane.ERROR_MESSAGE);
                return;
            }

        } else if (status.toString().equals("WANTED")) {
            if (this.txtCrimeControlFirtName.getText().isEmpty()
                || this.txtCrimeControlFirtName.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Full name of wanted person is required.", "Invalid", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        //Photos will be sent first
        String img_file_name = this.imgCrimeControlPhoto.getImageString();

        //get unique number for photo
        long unique_number = ServerManager.getUniqueNumber();
        if (unique_number == -1) {
            int option = JOptionPane.showConfirmDialog(this, "Initialize photo send failed!\nCheck your connection.\nTry again?", "Unsent Photo", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (option == JOptionPane.NO_OPTION) {
                return;
            }
            txtCrimeControlSaveActionPerformed(evt);
        }

        //send photo
        String remote_staff_photo_filename = ServerManager.sendPhotoToServerByFTP(img_file_name, unique_number);
        if (remote_staff_photo_filename == null || remote_staff_photo_filename.isEmpty()) {
            int option = JOptionPane.showConfirmDialog(this, "Could not send photo!\nCheck your connection.\nTry again?", "Unsent Photo", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (option == JOptionPane.NO_OPTION) {
                return;
            }
            txtCrimeControlSaveActionPerformed(evt);
        }

        SQLColumn[] sql_columns = {new SQLColumn("STATION_CATEGORY", ServerManager.division),
            new SQLColumn("STATE", ServerManager.IncidenceState),
            new SQLColumn("LGA", ServerManager.IncidenceLGA),
            new SQLColumn("FIRST_NAME", this.txtCrimeControlFirtName.getText()),
            new SQLColumn("SURNAME", this.txtCrimeControlSurname.getText()),
            new SQLColumn("SEX", this.txtCrimeControlSex.getSelectedItem()),
            new SQLColumn("DATE_OF_BIRTH", this.txtCrimeControlDateOfBirth.getEditor().getText()),
            new SQLColumn("PHONE_NO", this.txtCrimeControlPhoneNo.getText()),
            new SQLColumn("CASE_STATUS", status.toString()),
            new SQLColumn("REASON_FOR_ARREST", this.txtCrimeControlReasonOfArrest.getText()),
            new SQLColumn("DATE_OF_ARREST", this.txtCrimeControlDateArrested.getEditor().getText()),
            new SQLColumn("PHOTO_FILE_NAME", this.imgCrimeControlPhoto.getImageString())};

        DBResource dBResource = null;

        try {

            dBResource = ServerManager.insertStatementAutoPolice("crime_case", sql_columns, true);
            JOptionPane.showMessageDialog(this, "Record has been sucessfully added.",
                "Successful", JOptionPane.OK_OPTION);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Failed to add record.",
                "Failed", JOptionPane.OK_OPTION);
            ex.printStackTrace();
        } finally {
            if (dBResource != null) {
                dBResource.close();
            }
        }
    }//GEN-LAST:event_txtCrimeControlSaveActionPerformed

    private void txtCrimeControlFirtNametxtCrimeControlNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCrimeControlFirtNametxtCrimeControlNameFocusLost

        new Thread(new Runnable() {

            @Override
            public void run() {
                searchPreviouCaseOnPerson(txtCrimeControlFirtName.getText(), txtCrimeControlSurname.getText());
            }
        }).start();
    }//GEN-LAST:event_txtCrimeControlFirtNametxtCrimeControlNameFocusLost
    synchronized private void searchPreviouCaseOnPerson(String first_name, String surname) {

        DBResource dBResource = null;

        try {

            String columns[] = new String[]{"SN",
                "FIRST_NAME",
                "SURNAME",
                "SEX",
                "DATE_OF_BIRTH",
                "PHONE_NO",
                "REASON_FOR_ARREST",
                "DATE_OF_ARREST",
                "CASE_STATUS",
                "STATUS_DATE",
                "STATE",
                "LGA",
                "STATION_CATEGORY",
                "PHOTO_FILE_NAME"};

            String condition = " WHERE FIRST_NAME='" + first_name + "'"
                    + "AND SURNAME='" + surname + "'";

            dBResource = ServerManager.sendQueryAutoPolice("crime_case", columns, condition);
            this.lstPreviousCaseSearchList.setListData(new Vector());//first clear
            Vector v = new Vector();
            ServerManager.crime_person = new HashMap();
            int index = -1;//used for track the position on the list of names
            ServerManager.PreviousCaseOfPerson = 0;
            while (dBResource.rs.next()) {
                String fname = dBResource.rs.getString("FIRST_NAME");
                String lname = dBResource.rs.getString("SURNAME");
                String full_name = fname + " " + lname;
                v.add(full_name);
                Person person = new Person();
                person.serial_no = dBResource.rs.getInt("SN");;
                person.first_name = fname;
                person.last_name = lname;
                person.age = dBResource.rs.getString("DATE_OF_BIRTH");
                person.sex = dBResource.rs.getString("SEX");
                person.phone_no = dBResource.rs.getString("PHONE_NO");
                person.reason_for_arrest = dBResource.rs.getString("REASON_FOR_ARREST");
                person.date_of_arrest = dBResource.rs.getString("DATE_OF_ARREST");
                person.photo_file_name = dBResource.rs.getString("PHOTO_FILE_NAME");
                person.case_status = dBResource.rs.getString("CASE_STATUS");
                person.status_date = dBResource.rs.getString("STATUS_DATE");
                person.state = dBResource.rs.getString("STATE");
                person.lga = dBResource.rs.getString("LGA");
                person.station = dBResource.rs.getString("STATION_CATEGORY");
                index++;
                ServerManager.crime_person.put(index, person);

                ServerManager.imageLoader.loadImage(person.photo_file_name, this.imgCrimeControlPhoto);//load the image
            }

            ServerManager.PreviousCaseOfPerson = index+1;
            this.lstPreviousCaseSearchList.setListData(v);

            if (ServerManager.PreviousCaseOfPerson > 0) {
                cmdCrimeControlRelatedCase.setEnabled(true);
                String _case = ServerManager.PreviousCaseOfPerson > 1 ? " cases " : " case ";
                lblPreviousCaseIndicator.setText("Found " + ServerManager.PreviousCaseOfPerson + _case
                        + " relating to " + first_name + " " + surname);
            }

        } catch (SQLException ex) {
            Logger.getLogger(ServerManager.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            if(dBResource!=null){
                dBResource.close();
            }
        }

    }

    private void txtCrimeControlSurnametxtCrimeControlNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCrimeControlSurnametxtCrimeControlNameFocusLost

        new Thread(new Runnable() {

            @Override
            public void run() {
                searchPreviouCaseOnPerson(txtCrimeControlFirtName.getText(), txtCrimeControlSurname.getText());
            }
        }).start();
    }//GEN-LAST:event_txtCrimeControlSurnametxtCrimeControlNameFocusLost

    private void txtCrimeControlDateArrestedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCrimeControlDateArrestedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCrimeControlDateArrestedActionPerformed

    private void txtCrimeControlBrowsePhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCrimeControlBrowsePhotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCrimeControlBrowsePhotoActionPerformed

    private void txtCrimeControlCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCrimeControlCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_txtCrimeControlCancelActionPerformed

    
    private Date getDefaultDate(){        
        return ServerManager.getDefaultDate();
    }
    
    
    Rectangle getCenteredBounds(double percent_screen_width, double percent_screen_height) {
        int task_bar_height = 37;
        int screen_width = (int) this.getGraphicsConfiguration().getBounds().getWidth();
        int screen_height = (int) this.getGraphicsConfiguration().getBounds().getHeight();
        int w = (int) (percent_screen_width * screen_width);
        int h = (int) (percent_screen_height * screen_height);

        int x = (int) ((screen_width - w) / 2);
        int y = (int) ((screen_height - h) / 2);

        if (h + y > screen_height - task_bar_height) {
            y = 0;
            h = screen_height - task_bar_height;
        }
        return new Rectangle(x, y, w, h);
    }

    private Dimension getFormDimension(double percent_screen_width, double percent_screen_height) {

        int screen_width = (int) this.getGraphicsConfiguration().getBounds().getWidth();
        int screen_height = (int) this.getGraphicsConfiguration().getBounds().getHeight();
        int w = (int) (percent_screen_width * screen_width);
        int h = (int) (percent_screen_height * screen_height);

        return new Dimension(w, h);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrimeControlDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrimeControlDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrimeControlDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrimeControlDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CrimeControlDialog dialog = new CrimeControlDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPaneCrimeControl;
    private javax.swing.JComboBox cboCrimeControlStatus;
    private javax.swing.JButton cmdCrimeControlRelatedCase;
    private org.jdesktop.swingx.JXImageView imgCrimeControlPhoto;
    private org.jdesktop.swingx.JXImageView imgPreviousCasePhoto;
    private javax.swing.JLabel jLabel168;
    private javax.swing.JLabel jLabel170;
    private javax.swing.JLabel jLabel171;
    private javax.swing.JLabel jLabel172;
    private javax.swing.JLabel jLabel173;
    private javax.swing.JLabel jLabel188;
    private javax.swing.JLabel jLabel189;
    private javax.swing.JLabel jLabel200;
    private javax.swing.JLabel jLabel203;
    private javax.swing.JLabel jLabel204;
    private javax.swing.JLabel jLabel205;
    private javax.swing.JLabel jLabel206;
    private javax.swing.JLabel jLabel207;
    private javax.swing.JLabel jLabel208;
    private javax.swing.JLabel jLabel209;
    private javax.swing.JLabel jLabel210;
    private javax.swing.JLabel jLabel211;
    private javax.swing.JLabel jLabel212;
    private javax.swing.JLabel jLabel213;
    private javax.swing.JLabel jLabel214;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JLabel lblPreviousCaseAge;
    private javax.swing.JLabel lblPreviousCaseDateOfArrest;
    private javax.swing.JLabel lblPreviousCaseFirstName;
    private javax.swing.JLabel lblPreviousCaseIndicator;
    private javax.swing.JLabel lblPreviousCaseLGA;
    private javax.swing.JTextArea lblPreviousCaseReasonForArrest;
    private javax.swing.JLabel lblPreviousCaseSex;
    private javax.swing.JLabel lblPreviousCaseState;
    private javax.swing.JLabel lblPreviousCaseStation;
    private javax.swing.JLabel lblPreviousCaseStatus;
    private javax.swing.JLabel lblPreviousCaseStatusDate;
    private javax.swing.JLabel lblPreviousCaseSurname;
    private javax.swing.JList lstPreviousCaseSearchList;
    private javax.swing.JPanel pnlCrimeControlCase;
    private javax.swing.JPanel pnlPreciousCaseIndicator;
    public javax.swing.JPanel pnlPreviousCaseInfo;
    private javax.swing.JButton txtCrimeControlBrowsePhoto;
    private javax.swing.JButton txtCrimeControlCancel;
    private org.jdesktop.swingx.JXDatePicker txtCrimeControlDateArrested;
    private org.jdesktop.swingx.JXDatePicker txtCrimeControlDateOfBirth;
    private javax.swing.JTextField txtCrimeControlFirtName;
    private javax.swing.JTextField txtCrimeControlPhoneNo;
    private javax.swing.JTextArea txtCrimeControlReasonOfArrest;
    private javax.swing.JButton txtCrimeControlSave;
    private javax.swing.JComboBox txtCrimeControlSex;
    private javax.swing.JTextField txtCrimeControlSurname;
    // End of variables declaration//GEN-END:variables
}
