/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manager;

import java.awt.Dimension;
import java.awt.Rectangle;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import manager.ui.model.MngVehicleTheftReportModel;
import manager.util.SQLColumn;

/**
 *
 * @author user
 */
public class ManageVehicleTheftDialog extends javax.swing.JDialog {
    
static MngVehicleTheftReportModel mngVehicleTheftReportModel = new MngVehicleTheftReportModel();
    /**
     * Creates new form ManageVehicleTheftDialog
     */
    public ManageVehicleTheftDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        lblMngVehiclePlateNo = new javax.swing.JLabel();
        lblMngVehicleName = new javax.swing.JLabel();
        lblMngVehicleModel = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        lblMngVIN = new javax.swing.JLabel();
        cmdMngVehicleTheftUpdate = new javax.swing.JButton();
        jLabel89 = new javax.swing.JLabel();
        lblMngEngineNo = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        lblMngNumTimesStolen = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        dpMngRecoveryTime = new org.jdesktop.swingx.JXDatePicker();
        imgMngVehicleImageView = new org.jdesktop.swingx.JXImageView();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel94 = new javax.swing.JLabel();
        lblMngVehicleOwnerFullName = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        lblMngVehiclePhoneNo = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        lblMngVehicleOwnerSex = new javax.swing.JLabel();
        imgMngVehicleOwnerImageView = new org.jdesktop.swingx.JXImageView();
        jLabel100 = new javax.swing.JLabel();
        lblMngVehicleOwnerAge = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        lblMngVehicleOwnerAddress = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        lblMngVehicleTheftIncidenceLGAOfOrigin = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        lblMngDateTimeStolen = new javax.swing.JLabel();
        lblMngVehicleTheftIncidenceStateOfOrigin = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        mngVehicleTheftReportTable = new manager.ui.VehicleTheftReportTable();
        cboMngVehicleStatus = new javax.swing.JComboBox();
        jLabel140 = new javax.swing.JLabel();
        lblMngVehicleIMEI = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Vehicle Theft Report");
        setBounds(this.getCenteredBounds(0.9, 0.95));
        setPreferredSize(this.getFormDimension(0.9, 0.95));

        jLabel80.setText("Status");

        jLabel81.setText("Plate no.");

        jLabel82.setText("Vehicle name");

        jLabel83.setText("Vehicle model");

        jLabel87.setText("VIN");

        cmdMngVehicleTheftUpdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmdMngVehicleTheftUpdate.setText("Edit");
        cmdMngVehicleTheftUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMngVehicleTheftUpdateActionPerformed(evt);
            }
        });

        jLabel89.setText("Engine no.");

        jLabel91.setText("No. of times stolen");

        jLabel93.setText("Datetime of recovery");

        dpMngRecoveryTime.setEditable(false);
        dpMngRecoveryTime.setFormats(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss"));

        javax.swing.GroupLayout imgMngVehicleImageViewLayout = new javax.swing.GroupLayout(imgMngVehicleImageView);
        imgMngVehicleImageView.setLayout(imgMngVehicleImageViewLayout);
        imgMngVehicleImageViewLayout.setHorizontalGroup(
            imgMngVehicleImageViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        imgMngVehicleImageViewLayout.setVerticalGroup(
            imgMngVehicleImageViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jLabel94.setText("Owner full name");

        jLabel96.setText("Phone number");

        jLabel98.setText("Sex");

        javax.swing.GroupLayout imgMngVehicleOwnerImageViewLayout = new javax.swing.GroupLayout(imgMngVehicleOwnerImageView);
        imgMngVehicleOwnerImageView.setLayout(imgMngVehicleOwnerImageViewLayout);
        imgMngVehicleOwnerImageViewLayout.setHorizontalGroup(
            imgMngVehicleOwnerImageViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
        );
        imgMngVehicleOwnerImageViewLayout.setVerticalGroup(
            imgMngVehicleOwnerImageViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 113, Short.MAX_VALUE)
        );

        jLabel100.setText("Age");

        jLabel102.setText("Address");

        jLabel104.setText("LGA of origin");

        jLabel115.setText("Datetime stolen");

        jLabel130.setText("State of origin");

        mngVehicleTheftReportTable.setModel(this.mngVehicleTheftReportModel);
        mngVehicleTheftReportTable.setRowHeight(60);
        mngVehicleTheftReportTable.setSelectionModel(setPrefetchVehicleTheftSelectionModel());
        jScrollPane11.setViewportView(mngVehicleTheftReportTable);

        cboMngVehicleStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "O.K", "RECOVERED", "STOLEN" }));
        cboMngVehicleStatus.setSelectedIndex(-1);
        cboMngVehicleStatus.setEnabled(false);

        jLabel140.setText("Vehicle IMEI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel89)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel87, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMngEngineNo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cmdMngVehicleTheftUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblMngVehicleIMEI, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(3, 3, 3)
                                                    .addComponent(lblMngVIN, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(18, 18, 18)
                                            .addComponent(imgMngVehicleImageView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel91, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16)
                                        .addComponent(lblMngNumTimesStolen, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel115, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)
                                        .addComponent(lblMngDateTimeStolen, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel93, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15)
                                        .addComponent(dpMngRecoveryTime, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(15, 15, 15)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblMngVehiclePlateNo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblMngVehicleName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblMngVehicleModel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel140, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imgMngVehicleOwnerImageView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cboMngVehicleStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel94)
                                            .addComponent(jLabel96, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel98)
                                            .addComponent(jLabel100)
                                            .addComponent(jLabel102))
                                        .addGap(46, 46, 46)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblMngVehicleOwnerFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblMngVehiclePhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblMngVehicleOwnerSex, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblMngVehicleOwnerAge, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblMngVehicleOwnerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblMngVehicleTheftIncidenceLGAOfOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel130)
                                        .addGap(56, 56, 56)
                                        .addComponent(lblMngVehicleTheftIncidenceStateOfOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel104)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel80)
                            .addComponent(cboMngVehicleStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdMngVehicleTheftUpdate))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgMngVehicleImageView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel81)
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel82)
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel83))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblMngVehiclePlateNo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(lblMngVehicleName, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(lblMngVehicleModel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel140)
                                    .addComponent(lblMngVehicleIMEI, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel87)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel89))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblMngVIN, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(lblMngEngineNo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel91)
                                    .addComponent(lblMngNumTimesStolen, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel115)
                                    .addComponent(lblMngDateTimeStolen, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel93)
                                    .addComponent(dpMngRecoveryTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel94)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel96)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel98)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel100)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel102))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblMngVehicleOwnerFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(lblMngVehiclePhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(lblMngVehicleOwnerSex, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(lblMngVehicleOwnerAge, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(lblMngVehicleOwnerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(imgMngVehicleOwnerImageView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel104)
                            .addComponent(lblMngVehicleTheftIncidenceLGAOfOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel130))
                            .addComponent(lblMngVehicleTheftIncidenceStateOfOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdMngVehicleTheftUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMngVehicleTheftUpdateActionPerformed

        if (cmdMngVehicleTheftUpdate.getText().equalsIgnoreCase("Edit")) {
            this.cboMngVehicleStatus.setEnabled(true);
            this.dpMngRecoveryTime.setEditable(true);
            cmdMngVehicleTheftUpdate.setText("Update");
            return;
        }

        if (this.cboMngVehicleStatus.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Status not be empty", "Invalid", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            SQLColumn[] column = new SQLColumn[]{new SQLColumn("STATUS", this.cboMngVehicleStatus.getSelectedItem().toString()),
                new SQLColumn("DATE_TIME_RECOVERED", this.dpMngRecoveryTime.getEditor().getText())};
            ServerManager.updateStatementAutoPolice("vehicle_owners", column, "WHERE PLATE_NO='" + ServerManager.SelectedVehiclPLateNo + "'", true);

            this.cboMngVehicleStatus.setEnabled(false);
            this.dpMngRecoveryTime.setEditable(false);
            cmdMngVehicleTheftUpdate.setText("Edit");

            JOptionPane.showMessageDialog(this, "Updated successfully.", "Sucess", JOptionPane.INFORMATION_MESSAGE);

        } catch (SQLException ex) {
            Logger.getLogger(ServerManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmdMngVehicleTheftUpdateActionPerformed
    ListSelectionModel setPrefetchVehicleTheftSelectionModel() {
        ListSelectionModel listSelectionModel = this.mngVehicleTheftReportTable.getSelectionModel();
        listSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        listSelectionModel.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {

                ServerManager.SelectedVehiclPLateNo = mngVehicleTheftReportTable.getSelectedPlateNo();
                if (ServerManager.SelectedVehiclPLateNo.equals(ServerManager.LastSelectedVehiclPLatNo)) {
                    return;//avoid repetition which do occur - perhap due to java ui bug
                }
                ServerManager.LastSelectedVehiclPLatNo = ServerManager.SelectedVehiclPLateNo;

                setVehicleOwnerInfoByPlateNo();
            }
        });

        return listSelectionModel;
    }
    void setVehicleOwnerInfoByPlateNo() {

        DBResource dBResource = null;
        try {

            String[] columns = {"SN",
                "FIRST_NAME",
                "MIDDLE_NAME",
                "LAST_NAME",
                "ORGANIZATION",
                "SEX",
                "DATE_OF_BIRTH",
                "OWNER_PHONE_NO",
                "ADDRESS",
                "LGA_OF_ORIGIN",
                "STATE_OF_ORIGIN",
                "VIN",
                "PLATE_NO",
                "FINGER_PRINT_ID",
                "ENGINE_NO",
                "VEHICLE_NAME",
                "VEHICLE_MODEL",
                "VEHICLE_IMEI",
                "DATE_OWNED",
                "DATETIME_STOLEN",
                "DATE_TIME_RECOVERED",
                "STATUS",
                "NO_OF_TIMES_STOLEN",
                "REMARKS",
                "OWNER_PHOTO_FILE_NAME",
                "VEHICLE_PHOTO_FILE_NAME"};

            dBResource = ServerManager.sendQueryAutoPolice("vehicle_owners",
                    columns,
                    " WHERE PLATE_NO='" + ServerManager.SelectedVehiclPLateNo + "'");

            String owner_photo_file_name = "";
            String vehicle_photo_file_name = "";

            if (dBResource.rs.next()) {

                String first_name = dBResource.rs.getString("FIRST_NAME");
                String middle_name = dBResource.rs.getString("MIDDLE_NAME");
                String last_name = dBResource.rs.getString("LAST_NAME");
                String organization = dBResource.rs.getString("ORGANIZATION");

                String full_name = organization.isEmpty() ? (first_name + (middle_name.isEmpty() ? " " : (" " + middle_name + " ")) + last_name) : organization;

                int vehicle_imei = dBResource.rs.getInt("VEHICLE_IMEI");
                String str_vehicle_imei = vehicle_imei == -1 ? "" : ("" + vehicle_imei);
                this.cboMngVehicleStatus.setSelectedItem(dBResource.rs.getString("STATUS"));
                this.lblMngVehiclePlateNo.setText(dBResource.rs.getString("PLATE_NO"));
                this.lblMngVehicleName.setText(dBResource.rs.getString("VEHICLE_NAME"));
                this.lblMngVehicleModel.setText(dBResource.rs.getString("VEHICLE_MODEL"));
                this.lblMngVehicleIMEI.setText(str_vehicle_imei);
                this.lblMngVIN.setText(dBResource.rs.getString("VIN"));
                this.lblMngEngineNo.setText(dBResource.rs.getString("ENGINE_NO"));
                this.lblMngNumTimesStolen.setText(dBResource.rs.getString("NO_OF_TIMES_STOLEN"));
                this.lblMngDateTimeStolen.setText(dBResource.rs.getString("DATETIME_STOLEN"));
                this.dpMngRecoveryTime.getEditor().setText(dBResource.rs.getString("DATE_TIME_RECOVERED"));

                this.lblMngVehicleOwnerFullName.setText(full_name);
                this.lblMngVehiclePhoneNo.setText(dBResource.rs.getString("OWNER_PHONE_NO"));
                this.lblMngVehicleOwnerSex.setText(dBResource.rs.getString("SEX"));
                this.lblMngVehicleOwnerAge.setText(dBResource.rs.getString("DATE_OF_BIRTH"));//come back for age computation
                this.lblMngVehicleOwnerAddress.setText(dBResource.rs.getString("ADDRESS"));
                this.lblMngVehicleTheftIncidenceLGAOfOrigin.setText(dBResource.rs.getString("LGA_OF_ORIGIN"));
                this.lblMngVehicleTheftIncidenceStateOfOrigin.setText(dBResource.rs.getString("STATE_OF_ORIGIN"));

                vehicle_photo_file_name = dBResource.rs.getString("VEHICLE_PHOTO_FILE_NAME");
                owner_photo_file_name = dBResource.rs.getString("OWNER_PHOTO_FILE_NAME");

            }

            try {//display vehicle photo
                if (!vehicle_photo_file_name.isEmpty()) {
                    imgMngVehicleImageView.setImage(new URL(vehicle_photo_file_name));
                }
            } catch (MalformedURLException ex) {
                Logger.getLogger(ServerManager.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(ServerManager.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {//display owner photo
                if (!owner_photo_file_name.isEmpty()) {
                    imgMngVehicleOwnerImageView.setImage(new URL(owner_photo_file_name));
                }
            } catch (MalformedURLException ex) {
                Logger.getLogger(ServerManager.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(ServerManager.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ServerManager.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            if (dBResource != null) {
                dBResource.close();
            }
        }
    }
    
    Rectangle getCenteredBounds(double percent_screen_width, double percent_screen_height) {
        int task_bar_height = 37;
        int screen_width = (int) this.getGraphicsConfiguration().getBounds().getWidth();
        int screen_height = (int) this.getGraphicsConfiguration().getBounds().getHeight();
        int w = (int) (percent_screen_width * screen_width);
        int h = (int) (percent_screen_height * screen_height);

        int x = (int) ((screen_width - w) / 2);
        int y = (int) ((screen_height - h) / 2);

        if (h + y > screen_height - task_bar_height) {
            y = 0;
            h = screen_height - task_bar_height;
        }
        return new Rectangle(x, y, w, h);
    }

    private Dimension getFormDimension(double percent_screen_width, double percent_screen_height) {

        int screen_width = (int) this.getGraphicsConfiguration().getBounds().getWidth();
        int screen_height = (int) this.getGraphicsConfiguration().getBounds().getHeight();
        int w = (int) (percent_screen_width * screen_width);
        int h = (int) (percent_screen_height * screen_height);

        return new Dimension(w, h);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageVehicleTheftDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageVehicleTheftDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageVehicleTheftDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageVehicleTheftDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManageVehicleTheftDialog dialog = new ManageVehicleTheftDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboMngVehicleStatus;
    private javax.swing.JButton cmdMngVehicleTheftUpdate;
    private org.jdesktop.swingx.JXDatePicker dpMngRecoveryTime;
    private org.jdesktop.swingx.JXImageView imgMngVehicleImageView;
    private org.jdesktop.swingx.JXImageView imgMngVehicleOwnerImageView;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblMngDateTimeStolen;
    private javax.swing.JLabel lblMngEngineNo;
    private javax.swing.JLabel lblMngNumTimesStolen;
    private javax.swing.JLabel lblMngVIN;
    private javax.swing.JLabel lblMngVehicleIMEI;
    private javax.swing.JLabel lblMngVehicleModel;
    private javax.swing.JLabel lblMngVehicleName;
    private javax.swing.JLabel lblMngVehicleOwnerAddress;
    private javax.swing.JLabel lblMngVehicleOwnerAge;
    private javax.swing.JLabel lblMngVehicleOwnerFullName;
    private javax.swing.JLabel lblMngVehicleOwnerSex;
    private javax.swing.JLabel lblMngVehiclePhoneNo;
    private javax.swing.JLabel lblMngVehiclePlateNo;
    private javax.swing.JLabel lblMngVehicleTheftIncidenceLGAOfOrigin;
    private javax.swing.JLabel lblMngVehicleTheftIncidenceStateOfOrigin;
    private manager.ui.VehicleTheftReportTable mngVehicleTheftReportTable;
    // End of variables declaration//GEN-END:variables
}
