/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manager;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.JSONObject;

/**
 *
 * @author user
 */
public class NewReportDialog extends javax.swing.JDialog {
    
    private String currentCardNewReport;
    private String previousCardNewReport;
    /**
     * Creates new form NewReportDialog
     */
    public NewReportDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNewReport = new javax.swing.JPanel();
        pnlReportCategory = new javax.swing.JPanel();
        jLabel131 = new javax.swing.JLabel();
        cboReportCategoryNewReport = new javax.swing.JComboBox();
        txtReporterFirstNameNewReport = new javax.swing.JTextField();
        jLabel133 = new javax.swing.JLabel();
        jLabel135 = new javax.swing.JLabel();
        txtReporterLastNameNewReport = new javax.swing.JTextField();
        jLabel136 = new javax.swing.JLabel();
        jLabel137 = new javax.swing.JLabel();
        cboReporterSexNewReport = new javax.swing.JComboBox();
        txtReporterAgeNewReport = new javax.swing.JTextField();
        jLabel141 = new javax.swing.JLabel();
        txtReporterPhoneNoNewReport = new javax.swing.JTextField();
        jLabel146 = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        txaIncidenceLocationNewReport = new javax.swing.JTextArea();
        pnlAssaultReport = new javax.swing.JPanel();
        pnlTheftReport = new javax.swing.JPanel();
        cboTheftTypeNewReport = new javax.swing.JComboBox();
        jLabel132 = new javax.swing.JLabel();
        pnlMissingPersonReport = new javax.swing.JPanel();
        jLabel148 = new javax.swing.JLabel();
        jLabel150 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel153 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel154 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel155 = new javax.swing.JLabel();
        jLabel156 = new javax.swing.JLabel();
        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();
        pnlMurderReport = new javax.swing.JPanel();
        pnlThreatReport = new javax.swing.JPanel();
        pnlVehicleTheft = new javax.swing.JPanel();
        jLabel142 = new javax.swing.JLabel();
        txtVehiclePlateNoNewReport = new javax.swing.JTextField();
        jLabel144 = new javax.swing.JLabel();
        jLabel145 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        lblVehicleOwnerNewReport = new javax.swing.JLabel();
        lblVehicleNameNewReport = new javax.swing.JLabel();
        jLabel147 = new javax.swing.JLabel();
        lblVehicleModelNewReport = new javax.swing.JLabel();
        jLabel149 = new javax.swing.JLabel();
        lblVehicleEngineNoNewReport = new javax.swing.JLabel();
        jLabel151 = new javax.swing.JLabel();
        jSeparator20 = new javax.swing.JSeparator();
        jLabel152 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        txaVhicleTheftDetailsNewReport = new javax.swing.JTextArea();
        lblVehicleIMEINewReport = new javax.swing.JLabel();
        cmdSearchVehicleInfoNewReport = new javax.swing.JButton();
        imgVehicleOwnerPhotoNewReport = new org.jdesktop.swingx.JXImageView();
        imgVehiclePhotoNewReport = new org.jdesktop.swingx.JXImageView();
        jLabel143 = new javax.swing.JLabel();
        lblVehicleStatusNewReport = new javax.swing.JLabel();
        pnlMoneyTheftReport = new javax.swing.JPanel();
        pnlEquipmentTheftReport = new javax.swing.JPanel();
        jXTitledPanel1 = new org.jdesktop.swingx.JXTitledPanel();
        jPanel15 = new javax.swing.JPanel();
        cmdBackNewReport = new javax.swing.JButton();
        cmdNextNewReport = new javax.swing.JButton();
        cmdFinishNewReport = new javax.swing.JButton();
        cmdCancelNewReport = new javax.swing.JButton();
        cmdHelpNewReport = new javax.swing.JButton();

        pnlNewReport.setLayout(new java.awt.CardLayout());

        jLabel131.setText("Report category");

        cboReportCategoryNewReport.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Assault", "Threat", "Murder", "Theft", "Missing Person", "Accident" }));
        cboReportCategoryNewReport.setSelectedIndex(-1);
        cboReportCategoryNewReport.setToolTipText("");
        cboReportCategoryNewReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboReportCategoryNewReportActionPerformed(evt);
            }
        });

        txtReporterFirstNameNewReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReporterFirstNameNewReportActionPerformed(evt);
            }
        });

        jLabel133.setText("Reporter's first name");

        jLabel135.setText("Reporter's last name");

        jLabel136.setText("Reporter's sex");

        jLabel137.setText("Reporter's age");

        cboReporterSexNewReport.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        cboReporterSexNewReport.setSelectedIndex(-1);
        cboReporterSexNewReport.setToolTipText("");

        jLabel141.setText("Reporter's phone no.");

        jLabel146.setText("Location of incidence");

        txaIncidenceLocationNewReport.setColumns(20);
        txaIncidenceLocationNewReport.setRows(5);
        jScrollPane16.setViewportView(txaIncidenceLocationNewReport);

        javax.swing.GroupLayout pnlReportCategoryLayout = new javax.swing.GroupLayout(pnlReportCategory);
        pnlReportCategory.setLayout(pnlReportCategoryLayout);
        pnlReportCategoryLayout.setHorizontalGroup(
            pnlReportCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportCategoryLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(pnlReportCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel137, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel133, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel135, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel136, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel141, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel146, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel131, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(pnlReportCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboReportCategoryNewReport, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReporterFirstNameNewReport, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReporterLastNameNewReport, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboReporterSexNewReport, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReporterAgeNewReport, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReporterPhoneNoNewReport, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        pnlReportCategoryLayout.setVerticalGroup(
            pnlReportCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportCategoryLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(pnlReportCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel133)
                    .addComponent(txtReporterFirstNameNewReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(pnlReportCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtReporterLastNameNewReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel135))
                .addGap(15, 15, 15)
                .addGroup(pnlReportCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel136)
                    .addComponent(cboReporterSexNewReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(pnlReportCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel137)
                    .addComponent(txtReporterAgeNewReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(pnlReportCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel141)
                    .addComponent(txtReporterPhoneNoNewReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlReportCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel146))
                .addGap(18, 18, 18)
                .addGroup(pnlReportCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cboReportCategoryNewReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel131))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pnlNewReport.add(pnlReportCategory, "Report Category");

        javax.swing.GroupLayout pnlAssaultReportLayout = new javax.swing.GroupLayout(pnlAssaultReport);
        pnlAssaultReport.setLayout(pnlAssaultReportLayout);
        pnlAssaultReportLayout.setHorizontalGroup(
            pnlAssaultReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        pnlAssaultReportLayout.setVerticalGroup(
            pnlAssaultReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );

        pnlNewReport.add(pnlAssaultReport, "Assault Report");

        cboTheftTypeNewReport.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Money", "Vehicle", "Equiment" }));
        cboTheftTypeNewReport.setSelectedIndex(-1);
        cboTheftTypeNewReport.setToolTipText("");

        jLabel132.setText("Type of theft");

        javax.swing.GroupLayout pnlTheftReportLayout = new javax.swing.GroupLayout(pnlTheftReport);
        pnlTheftReport.setLayout(pnlTheftReportLayout);
        pnlTheftReportLayout.setHorizontalGroup(
            pnlTheftReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTheftReportLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel132, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cboTheftTypeNewReport, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );
        pnlTheftReportLayout.setVerticalGroup(
            pnlTheftReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTheftReportLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(pnlTheftReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTheftTypeNewReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel132))
                .addContainerGap(201, Short.MAX_VALUE))
        );

        pnlNewReport.add(pnlTheftReport, "Theft Report");

        jLabel148.setText("First name");

        jLabel150.setText("Last name");

        jLabel153.setText("Sex");

        jLabel154.setText("Age");

        jLabel155.setText("Date last seen");

        jLabel156.setText("Provide information of the missing person");

        javax.swing.GroupLayout pnlMissingPersonReportLayout = new javax.swing.GroupLayout(pnlMissingPersonReport);
        pnlMissingPersonReport.setLayout(pnlMissingPersonReportLayout);
        pnlMissingPersonReportLayout.setHorizontalGroup(
            pnlMissingPersonReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMissingPersonReportLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(pnlMissingPersonReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel156, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMissingPersonReportLayout.createSequentialGroup()
                        .addGroup(pnlMissingPersonReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel155, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel154, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel153, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel150, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel148, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(pnlMissingPersonReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4)
                            .addComponent(jXDatePicker2, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        pnlMissingPersonReportLayout.setVerticalGroup(
            pnlMissingPersonReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMissingPersonReportLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel156)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMissingPersonReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel148)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMissingPersonReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel150)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMissingPersonReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel153)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMissingPersonReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel154)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMissingPersonReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel155)
                    .addComponent(jXDatePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(185, Short.MAX_VALUE))
        );

        pnlNewReport.add(pnlMissingPersonReport, "Missing Person Report");

        javax.swing.GroupLayout pnlMurderReportLayout = new javax.swing.GroupLayout(pnlMurderReport);
        pnlMurderReport.setLayout(pnlMurderReportLayout);
        pnlMurderReportLayout.setHorizontalGroup(
            pnlMurderReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        pnlMurderReportLayout.setVerticalGroup(
            pnlMurderReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        pnlNewReport.add(pnlMurderReport, "Murder Report");

        javax.swing.GroupLayout pnlThreatReportLayout = new javax.swing.GroupLayout(pnlThreatReport);
        pnlThreatReport.setLayout(pnlThreatReportLayout);
        pnlThreatReportLayout.setHorizontalGroup(
            pnlThreatReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        pnlThreatReportLayout.setVerticalGroup(
            pnlThreatReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        pnlNewReport.add(pnlThreatReport, "Threat Report");

        jLabel142.setText("Enter the plate no.");

        txtVehiclePlateNoNewReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehiclePlateNoNewReportActionPerformed(evt);
            }
        });
        txtVehiclePlateNoNewReport.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVehiclePlateNoNewReportKeyTyped(evt);
            }
        });

        jLabel144.setText("Vehicle owner");

        jLabel145.setText("Vehicle name");

        jLabel147.setText("Vehicle model ");

        jLabel149.setText("Vehicle Engine no.");

        jLabel151.setText("Vehicle IMEI");

        jLabel152.setText("Detials");

        txaVhicleTheftDetailsNewReport.setColumns(20);
        txaVhicleTheftDetailsNewReport.setRows(5);
        jScrollPane15.setViewportView(txaVhicleTheftDetailsNewReport);

        cmdSearchVehicleInfoNewReport.setText("Search");
        cmdSearchVehicleInfoNewReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSearchVehicleInfoNewReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout imgVehicleOwnerPhotoNewReportLayout = new javax.swing.GroupLayout(imgVehicleOwnerPhotoNewReport);
        imgVehicleOwnerPhotoNewReport.setLayout(imgVehicleOwnerPhotoNewReportLayout);
        imgVehicleOwnerPhotoNewReportLayout.setHorizontalGroup(
            imgVehicleOwnerPhotoNewReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        imgVehicleOwnerPhotoNewReportLayout.setVerticalGroup(
            imgVehicleOwnerPhotoNewReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout imgVehiclePhotoNewReportLayout = new javax.swing.GroupLayout(imgVehiclePhotoNewReport);
        imgVehiclePhotoNewReport.setLayout(imgVehiclePhotoNewReportLayout);
        imgVehiclePhotoNewReportLayout.setHorizontalGroup(
            imgVehiclePhotoNewReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        imgVehiclePhotoNewReportLayout.setVerticalGroup(
            imgVehiclePhotoNewReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        jLabel143.setText("Last known status");

        javax.swing.GroupLayout pnlVehicleTheftLayout = new javax.swing.GroupLayout(pnlVehicleTheft);
        pnlVehicleTheft.setLayout(pnlVehicleTheftLayout);
        pnlVehicleTheftLayout.setHorizontalGroup(
            pnlVehicleTheftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVehicleTheftLayout.createSequentialGroup()
                .addGroup(pnlVehicleTheftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVehicleTheftLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(pnlVehicleTheftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator19, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                            .addComponent(jSeparator20)))
                    .addGroup(pnlVehicleTheftLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel152, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVehicleTheftLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlVehicleTheftLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pnlVehicleTheftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVehicleTheftLayout.createSequentialGroup()
                        .addComponent(jLabel142)
                        .addGap(18, 18, 18)
                        .addComponent(txtVehiclePlateNoNewReport, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdSearchVehicleInfoNewReport))
                    .addGroup(pnlVehicleTheftLayout.createSequentialGroup()
                        .addGroup(pnlVehicleTheftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel144)
                            .addComponent(jLabel149, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel143, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel151, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel147, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel145, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(pnlVehicleTheftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblVehicleOwnerNewReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblVehicleNameNewReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblVehicleIMEINewReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblVehicleEngineNoNewReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblVehicleStatusNewReport, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(lblVehicleModelNewReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlVehicleTheftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(imgVehicleOwnerPhotoNewReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(imgVehiclePhotoNewReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 192, Short.MAX_VALUE))
        );
        pnlVehicleTheftLayout.setVerticalGroup(
            pnlVehicleTheftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVehicleTheftLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(pnlVehicleTheftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel142)
                    .addComponent(txtVehiclePlateNoNewReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdSearchVehicleInfoNewReport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(pnlVehicleTheftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlVehicleTheftLayout.createSequentialGroup()
                        .addGroup(pnlVehicleTheftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel144)
                            .addComponent(lblVehicleOwnerNewReport, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlVehicleTheftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel145)
                            .addComponent(lblVehicleNameNewReport, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlVehicleTheftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel147)
                            .addComponent(lblVehicleModelNewReport, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlVehicleTheftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel149)
                            .addComponent(lblVehicleEngineNoNewReport, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlVehicleTheftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel151)
                            .addComponent(lblVehicleIMEINewReport, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(pnlVehicleTheftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel143)
                            .addComponent(lblVehicleStatusNewReport, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVehicleTheftLayout.createSequentialGroup()
                        .addComponent(imgVehicleOwnerPhotoNewReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imgVehiclePhotoNewReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(jSeparator20, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlVehicleTheftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel152)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlNewReport.add(pnlVehicleTheft, "Vehicle Theft Report");

        javax.swing.GroupLayout pnlMoneyTheftReportLayout = new javax.swing.GroupLayout(pnlMoneyTheftReport);
        pnlMoneyTheftReport.setLayout(pnlMoneyTheftReportLayout);
        pnlMoneyTheftReportLayout.setHorizontalGroup(
            pnlMoneyTheftReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        pnlMoneyTheftReportLayout.setVerticalGroup(
            pnlMoneyTheftReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        pnlNewReport.add(pnlMoneyTheftReport, "Money Theft Report");

        javax.swing.GroupLayout pnlEquipmentTheftReportLayout = new javax.swing.GroupLayout(pnlEquipmentTheftReport);
        pnlEquipmentTheftReport.setLayout(pnlEquipmentTheftReportLayout);
        pnlEquipmentTheftReportLayout.setHorizontalGroup(
            pnlEquipmentTheftReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        pnlEquipmentTheftReportLayout.setVerticalGroup(
            pnlEquipmentTheftReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        pnlNewReport.add(pnlEquipmentTheftReport, "Equipment Theft Report");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(this.getCenteredBounds(0.7, 0.8));
        setPreferredSize(this.getFormDimension(0.7, 0.8));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jXTitledPanel1.setContentContainer(pnlNewReport);
        getContentPane().add(jXTitledPanel1);

        cmdBackNewReport.setText("< Back");
        cmdBackNewReport.setEnabled(false);
        cmdBackNewReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBackNewReportActionPerformed(evt);
            }
        });

        cmdNextNewReport.setText("Next >");
        cmdNextNewReport.setEnabled(false);
        cmdNextNewReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNextNewReportActionPerformed(evt);
            }
        });

        cmdFinishNewReport.setText("Finish");
        cmdFinishNewReport.setEnabled(false);
        cmdFinishNewReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFinishNewReportActionPerformed(evt);
            }
        });

        cmdCancelNewReport.setText("Cancel");
        cmdCancelNewReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelNewReportActionPerformed(evt);
            }
        });

        cmdHelpNewReport.setText("Help");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(191, Short.MAX_VALUE)
                .addComponent(cmdBackNewReport)
                .addGap(6, 6, 6)
                .addComponent(cmdNextNewReport)
                .addGap(6, 6, 6)
                .addComponent(cmdFinishNewReport)
                .addGap(6, 6, 6)
                .addComponent(cmdCancelNewReport)
                .addGap(6, 6, 6)
                .addComponent(cmdHelpNewReport)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdBackNewReport)
                    .addComponent(cmdNextNewReport)
                    .addComponent(cmdFinishNewReport)
                    .addComponent(cmdCancelNewReport)
                    .addComponent(cmdHelpNewReport))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel15);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdBackNewReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBackNewReportActionPerformed
        java.awt.CardLayout card_layout = (java.awt.CardLayout) pnlNewReport.getLayout();
        card_layout.show(pnlNewReport, previousCardNewReport);

        if (previousCardNewReport.equals("Report Category")) {
            cmdBackNewReport.setEnabled(false);
        }

        currentCardNewReport = previousCardNewReport;
    }//GEN-LAST:event_cmdBackNewReportActionPerformed

    private void cmdNextNewReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNextNewReportActionPerformed

        java.awt.CardLayout card_layout = (java.awt.CardLayout) pnlNewReport.getLayout();

        if (currentCardNewReport == null || currentCardNewReport.isEmpty()) {
            currentCardNewReport = "Report Category";
        }

        this.cmdFinishNewReport.setEnabled(false);

        switch (currentCardNewReport) {
            case "Report Category":
            doReportCategory(card_layout);
            this.cmdBackNewReport.setEnabled(true);
            break;
            case "Assault Report":
            doAssaultReport(card_layout);
            this.cmdBackNewReport.setEnabled(true);
            break;
            case "Theft Report":
            doTheftReport(card_layout);
            this.cmdBackNewReport.setEnabled(true);
            break;
            case "Missing Person Report":
            doMissingPersonReport(card_layout);
            this.cmdBackNewReport.setEnabled(true);
            break;
            case "Murder Report":
            doMurderReport(card_layout);
            this.cmdBackNewReport.setEnabled(true);
            break;
            case "Threat Report":
            doThreatReport(card_layout);
            this.cmdBackNewReport.setEnabled(true);
            break;
            case "Money Theft Report":
            doMoneyTheftReport(card_layout);
            this.cmdBackNewReport.setEnabled(true);
            break;
            case "Vehicle Theft Report":
            doVehicleTheftReport(card_layout);
            this.cmdBackNewReport.setEnabled(true);
            break;
            case "Equipment Theft Report":
            doEquipmentTheftReport(card_layout);
            this.cmdBackNewReport.setEnabled(true);
            break;
        }
    }//GEN-LAST:event_cmdNextNewReportActionPerformed

    private void cmdFinishNewReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFinishNewReportActionPerformed

        java.awt.CardLayout card_layout = (java.awt.CardLayout) pnlNewReport.getLayout();

        switch (currentCardNewReport) {
            case "Money Theft Report":
            doMoneyTheftReport(card_layout);
            this.cmdBackNewReport.setEnabled(true);
            break;
            case "Vehicle Theft Report":
            doVehicleTheftReport(card_layout);
            this.cmdBackNewReport.setEnabled(true);
            break;
            case "Equipment Theft Report":
            doEquipmentTheftReport(card_layout);
            this.cmdBackNewReport.setEnabled(true);
            break;
        }

        //finally
        this.setVisible(false);
        card_layout.show(pnlNewReport, "Report Category");// back to the first card
        this.dispose();
    }//GEN-LAST:event_cmdFinishNewReportActionPerformed

    private void cmdCancelNewReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelNewReportActionPerformed
        //initNewReportDlg();//NOT REQUIRED ANY MORE
        this.dispose();
    }//GEN-LAST:event_cmdCancelNewReportActionPerformed

    private void initNewReportDlg() {//NOT REQUIRED ANY MORE
        java.awt.CardLayout card_layout = (java.awt.CardLayout) pnlNewReport.getLayout();
        this.setVisible(true);
        card_layout.show(pnlNewReport, "Report Category");// back to the first card
        this.dispose();
    }

    private void cboReportCategoryNewReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboReportCategoryNewReportActionPerformed
        Object selected_obj = cboReportCategoryNewReport.getSelectedItem();
        if (selected_obj != null) {
            if (!this.cmdNextNewReport.isEnabled()) {
                this.cmdNextNewReport.setEnabled(true);
            }

        }
    }//GEN-LAST:event_cboReportCategoryNewReportActionPerformed

    private void txtReporterFirstNameNewReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReporterFirstNameNewReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReporterFirstNameNewReportActionPerformed

    private void txtVehiclePlateNoNewReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehiclePlateNoNewReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehiclePlateNoNewReportActionPerformed

    private void txtVehiclePlateNoNewReportKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVehiclePlateNoNewReportKeyTyped

        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            searchVehicleByPlateNo_NewReport();
        }
    }//GEN-LAST:event_txtVehiclePlateNoNewReportKeyTyped

    void searchVehicleByPlateNo_NewReport() {

        String vehicle_plate_no = this.txtVehiclePlateNoNewReport.getText();

        DBResource dBResource = null;
        try {

            String[] columns = {"SN",
                "FIRST_NAME",
                "MIDDLE_NAME",
                "LAST_NAME",
                "ORGANIZATION",
                "SEX",
                "DATE_OF_BIRTH",
                "OWNER_PHONE_NO",
                "ADDRESS",
                "LGA_OF_ORIGIN",
                "STATE_OF_ORIGIN",
                "VIN",
                "PLATE_NO",
                "FINGER_PRINT_ID",
                "ENGINE_NO",
                "VEHICLE_NAME",
                "VEHICLE_MODEL",
                "VEHICLE_IMEI",
                "DATE_OWNED",
                "DATETIME_STOLEN",
                "DATE_TIME_RECOVERED",
                "STATUS",
                "NO_OF_TIMES_STOLEN",
                "REMARKS",
                "OWNER_PHOTO_FILE_NAME",
                "VEHICLE_PHOTO_FILE_NAME"};

            dBResource = ServerManager.sendQueryAutoPolice("vehicle_owners",
                    columns,
                    " WHERE PLATE_NO='" + vehicle_plate_no + "'");

            String owner_photo_file_name = "";
            String vehicle_photo_file_name = "";

            if (dBResource.rs.next()) {

                String first_name = dBResource.rs.getString("FIRST_NAME");
                String middle_name = dBResource.rs.getString("MIDDLE_NAME");
                String last_name = dBResource.rs.getString("LAST_NAME");
                String organization = dBResource.rs.getString("ORGANIZATION");

                String full_name = organization.isEmpty() ? (first_name + (middle_name.isEmpty() ? " " : (" " + middle_name + " ")) + last_name) : organization;

                long vehicle_imei = dBResource.rs.getLong("VEHICLE_IMEI");
                String str_vehicle_imei = vehicle_imei == -1 ? "" : ("" + vehicle_imei);

                ServerManager.vehicle_plate_no_new_report = dBResource.rs.getString("PLATE_NO");
                this.lblVehicleNameNewReport.setText(dBResource.rs.getString("VEHICLE_NAME"));
                this.lblVehicleModelNewReport.setText(dBResource.rs.getString("VEHICLE_MODEL"));
                this.lblVehicleIMEINewReport.setText(str_vehicle_imei);
                this.lblVehicleEngineNoNewReport.setText(dBResource.rs.getString("ENGINE_NO"));
                this.lblVehicleOwnerNewReport.setText(full_name);
                this.lblVehicleStatusNewReport.setText(dBResource.rs.getString("STATUS"));

                vehicle_photo_file_name = dBResource.rs.getString("VEHICLE_PHOTO_FILE_NAME");
                owner_photo_file_name = dBResource.rs.getString("OWNER_PHOTO_FILE_NAME");

            }

            try {//display vehicle photo
                if (!vehicle_photo_file_name.isEmpty()) {
                    imgVehiclePhotoNewReport.setImage(new URL(vehicle_photo_file_name));
                }
            } catch (MalformedURLException ex) {
                Logger.getLogger(ServerManager.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(ServerManager.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {//display owner photo
                if (!owner_photo_file_name.isEmpty()) {
                    imgVehicleOwnerPhotoNewReport.setImage(new URL(owner_photo_file_name));
                }
            } catch (MalformedURLException ex) {
                Logger.getLogger(ServerManager.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(ServerManager.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ServerManager.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            if (dBResource != null) {
                dBResource.close();
            }
        }
    }

    private void cmdSearchVehicleInfoNewReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSearchVehicleInfoNewReportActionPerformed
        searchVehicleByPlateNo_NewReport();
    }//GEN-LAST:event_cmdSearchVehicleInfoNewReportActionPerformed

    private void doReportCategory(CardLayout card_layout) {

        Object selected_item = this.cboReportCategoryNewReport.getSelectedItem();

        if (selected_item == null) {
            JOptionPane.showMessageDialog(this, "No report category selected", "Invalid", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (this.txtReporterFirstNameNewReport.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No reporter first name!", "Invalid", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (this.txtReporterLastNameNewReport.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No reporter last name!", "Invalid", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (this.txtReporterAgeNewReport.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No reporter age!", "Invalid", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (this.cboReporterSexNewReport.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "No sex selected!", "Invalid", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (this.txtReporterPhoneNoNewReport.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No reporter phone!", "Invalid", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (this.txaIncidenceLocationNewReport.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No incidence location!", "Invalid", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String str_selected = selected_item.toString();

        switch (str_selected) {
            case "Assault":
                card_layout.show(pnlNewReport, "Assault Report");
                currentCardNewReport = "Assault Report";
                this.cmdBackNewReport.setEnabled(true);
                break;
            case "Theft":
                card_layout.show(pnlNewReport, "Theft Report");
                currentCardNewReport = "Theft Report";
                this.cmdBackNewReport.setEnabled(true);
                break;
            case "Missing Person":
                card_layout.show(pnlNewReport, "Missing Person Report");
                currentCardNewReport = "Missing Report";
                this.cmdBackNewReport.setEnabled(true);
                break;
            case "Murder":
                card_layout.show(pnlNewReport, "Murder Report");
                currentCardNewReport = "Murder Report";
                this.cmdBackNewReport.setEnabled(true);
                break;
            case "Threat":
                card_layout.show(pnlNewReport, "Threat Report");
                currentCardNewReport = "Threat Report";
                this.cmdBackNewReport.setEnabled(true);
                break;
        }

        this.cmdFinishNewReport.setEnabled(false);
        previousCardNewReport = "Report Category";

    }

    private void doAssaultReport(CardLayout card_layout) {

    }

    private void doTheftReport(CardLayout card_layout) {

        Object selected_item = this.cboTheftTypeNewReport.getSelectedItem();

        if (selected_item == null) {
            //display error message
            return;
        }

        String str_selected = selected_item.toString();

        switch (str_selected) {

            case "Money":
                card_layout.show(pnlNewReport, "Money Theft Report");
                currentCardNewReport = "Money Theft Report";
                this.cmdBackNewReport.setEnabled(true);
                this.cmdFinishNewReport.setEnabled(true);
                break;
            case "Vehicle":
                card_layout.show(pnlNewReport, "Vehicle Theft Report");
                currentCardNewReport = "Vehicle Theft Report";
                this.cmdBackNewReport.setEnabled(true);
                this.cmdFinishNewReport.setEnabled(true);
                break;
            case "Equipment":
                card_layout.show(pnlNewReport, "Equipment Theft Report");
                currentCardNewReport = "Equipment Theft Report";
                this.cmdBackNewReport.setEnabled(true);
                this.cmdFinishNewReport.setEnabled(true);
                break;

        }

        previousCardNewReport = "Theft Report";

    }

    private void doMissingPersonReport(CardLayout card_layout) {

    }

    private void doMurderReport(CardLayout card_layout) {

    }

    private void doThreatReport(CardLayout card_layout) {

    }

    private void doMoneyTheftReport(CardLayout card_layout) {

    }

    private void doVehicleTheftReport(CardLayout card_layout) {

        this.cmdNextNewReport.setEnabled(false);

        if (ServerManager.vehicle_plate_no_new_report == null
                || !ServerManager.vehicle_plate_no_new_report.equals(this.txtVehiclePlateNoNewReport.getText())) {
            searchVehicleByPlateNo_NewReport();
        }

        if (ServerManager.vehicle_plate_no_new_report == null
                || !ServerManager.vehicle_plate_no_new_report.equals(this.txtVehiclePlateNoNewReport.getText())) {
            int option = JOptionPane.showConfirmDialog(this, "Vehicle plate number could not be verified.\n"
                    + "Hint: Check connection or ensure the plate no is registered.\n\n"
                    + "Try again?",
                    "Unknown plate number", JOptionPane.YES_NO_OPTION);

            if (option == JOptionPane.YES_OPTION) {
                doVehicleTheftReport(card_layout);
            }
        } else {

            if (!sendVehicleReportToDivisionDB()) {
                int option = JOptionPane.showConfirmDialog(this, "Vehicle theft report process failed.\n", "Failed"
                        + "Reason: " + ServerManager.ReportFailReason + ".\n\n"
                        + "Try again?", JOptionPane.YES_NO_OPTION);

                if (option == JOptionPane.YES_OPTION) {
                    doVehicleTheftReport(card_layout);
                }
            }
        }

    }
    private boolean sendVehicleReportToDivisionDB() {

        Connection division_conn = null;
        PreparedStatement prd_stmt = null;
        Statement id_stm = null;
        ResultSet rs = null;
        JSONObject json = new JSONObject();
        boolean is_success = false;
        try {
            //get new division conncection for the incidence reprot
            division_conn = ServerManager.getDivisionConnection(ServerManager.IncidenceState);

            //first check message repetition by same user at quick succession
            Statement stmt = division_conn.createStatement();

            rs = stmt.executeQuery("SELECT PHONE_NO  FROM vehicle_theft_report "
                    + " WHERE "
                    + " PHONE_NO ='" + this.txtReporterPhoneNoNewReport.getText() + "'"
                    + " AND PLATE_NO ='" + this.txtVehiclePlateNoNewReport.getText() + "'"
                    + " AND REPORT_DETAILS  ='" + txaVhicleTheftDetailsNewReport.getText() + "'"
                    + " AND INCIDENCE_STATE ='" + ServerManager.IncidenceState + "'"
                    + " AND INCIDENCE_LGA ='" + ServerManager.IncidenceLGA + "'"
                    + " AND INCIDENCE_LOCATION ='" + txaIncidenceLocationNewReport.getText() + "'"
                    + " AND DETECTED_REPORTER_LOCATION =''"//no detection required is the report was made in police station
                    + " AND  NOW() - REPORT_TIME < 142834"//COME BACK FOR 142834 ABEG O!!!
            );

            if (rs.next()) {
                //json.put(Tag.message_type, Cmd.report_incidence);
                //json.put(Tag.feedback, Cmd.report_duplicate_rejected);

                //send(json);
                rs.close();
                stmt.close();
                division_conn.close();
                ServerManager.ReportFailReason = "duplicate report rejected";
                return is_success;
            }

            prd_stmt = division_conn.prepareStatement("INSERT INTO vehicle_theft_report ("
                    + " SN,"
                    + " PHONE_NO,"
                    + " REPORTER_FULL_NAME,"
                    + " INCIDENCE_STATE,"//incidence state
                    + " INCIDENCE_LGA,"//incidence LGA
                    + " INCIDENCE_LOCATION,"
                    + " REPORT_DETAILS,"
                    + " PLATE_NO,"
                    + " REPORTER_PHONE_NOS,"
                    + " DETECTED_REPORTER_LOCATION,"
                    + " REPORT_TIME"
                    + ")"
                    + "VALUES(0,?,?,?,?,?,?,?,?,?,?)");

            prd_stmt.setString(1, this.txtReporterPhoneNoNewReport.getText());
            prd_stmt.setString(2, this.txtReporterFirstNameNewReport.getText() + " " + this.txtReporterLastNameNewReport.getText());
            prd_stmt.setString(3, ServerManager.IncidenceState);
            prd_stmt.setString(4, ServerManager.IncidenceLGA);
            prd_stmt.setString(5, txaIncidenceLocationNewReport.getText());
            prd_stmt.setString(6, txaVhicleTheftDetailsNewReport.getText());
            prd_stmt.setString(7, this.txtVehiclePlateNoNewReport.getText());
            prd_stmt.setString(8, this.txtReporterPhoneNoNewReport.getText());//come back for actual implementation
            prd_stmt.setString(9, "");//no detection required is the report was made in police station
            prd_stmt.setTimestamp(10, new java.sql.Timestamp(new Date().getTime()));//come back

            prd_stmt.executeUpdate();

            id_stm = division_conn.createStatement();

            rs = id_stm.executeQuery("SELECT LAST_INSERT_ID()");
            String last_insert_id = "-1";
            if (rs.next()) {
                last_insert_id = rs.getString(1);
            }
            prd_stmt.close();

            try {
                //signify new report by update the LAST_REPORT_TIME            
                prd_stmt = division_conn.prepareStatement("UPDATE report_time_check SET "
                        + " LAST_REPORT_TIME=?");

                prd_stmt.setTimestamp(1, new java.sql.Timestamp(new Date().getTime()));//come back abeg o!!!

                int result = prd_stmt.executeUpdate();

                if (result < 1) {
                    //REMIND: PLEASE LOCK report_time_check ABEG O!!!!
                    stmt.executeUpdate("INSERT INTO  report_time_check "
                            + "(LAST_REPORT_TIME)"
                            + "VALUES(NOW())");
                }

                //json.put(Tag.message_type, Cmd.report_incidence);
                //json.put(Tag.feedback, Cmd.OK);
                //send(json);
                is_success = true;

            } catch (Exception ex) {
                //delete the last report using the last insert id

                id_stm = division_conn.createStatement();
                id_stm.executeUpdate("DELETE FROM vehicle_theft_report WHERE SN='" + last_insert_id + "'");

                //json.put(Tag.message_type, Cmd.report_incidence);
                //json.put(Tag.feedback, Cmd.ERROR);
                //send(json);
                ServerManager.ReportFailReason = "Problem occurred";
            }

        } catch (SQLException ex) {

            //json.put(Tag.message_type, Cmd.report_incidence);
            //json.put(Tag.feedback, Cmd.ERROR);
            //send(json);
            ServerManager.ReportFailReason = "Error occurred";
            Logger.getLogger(ServerManager.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            ServerManager.ReportFailReason = "Possibly no connection";
            Logger.getLogger(ServerManager.class.getName()).log(Level.SEVERE, null, ex);
        } finally {

            if (rs != null) {
                try {
                    rs.close();//mainly because of the rule of connection pool
                } catch (SQLException ex) {
                    Logger.getLogger(ServerManager.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            if (prd_stmt != null) {
                try {
                    prd_stmt.close();//mainly because of the rule of connection pool
                } catch (SQLException ex) {
                    Logger.getLogger(ServerManager.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            if (id_stm != null) {
                try {
                    id_stm.close();//mainly because of the rule of connection pool
                } catch (SQLException ex) {
                    Logger.getLogger(ServerManager.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            if (division_conn != null) {
                try {
                    division_conn.close();//mainly because of the rule of connection pool
                } catch (SQLException ex) {
                    Logger.getLogger(ServerManager.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }

        return is_success;
    }

    private void doEquipmentTheftReport(CardLayout card_layout) {

    }
    
    Rectangle getCenteredBounds(double percent_screen_width, double percent_screen_height) {
        int task_bar_height = 37;
        int screen_width = (int) this.getGraphicsConfiguration().getBounds().getWidth();
        int screen_height = (int) this.getGraphicsConfiguration().getBounds().getHeight();
        int w = (int) (percent_screen_width * screen_width);
        int h = (int) (percent_screen_height * screen_height);

        int x = (int) ((screen_width - w) / 2);
        int y = (int) ((screen_height - h) / 2);

        if (h + y > screen_height - task_bar_height) {
            y = 0;
            h = screen_height - task_bar_height;
        }
        return new Rectangle(x, y, w, h);
    }

    private Dimension getFormDimension(double percent_screen_width, double percent_screen_height) {

        int screen_width = (int) this.getGraphicsConfiguration().getBounds().getWidth();
        int screen_height = (int) this.getGraphicsConfiguration().getBounds().getHeight();
        int w = (int) (percent_screen_width * screen_width);
        int h = (int) (percent_screen_height * screen_height);

        return new Dimension(w, h);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewReportDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewReportDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewReportDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewReportDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewReportDialog dialog = new NewReportDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboReportCategoryNewReport;
    private javax.swing.JComboBox cboReporterSexNewReport;
    private javax.swing.JComboBox cboTheftTypeNewReport;
    private javax.swing.JButton cmdBackNewReport;
    private javax.swing.JButton cmdCancelNewReport;
    private javax.swing.JButton cmdFinishNewReport;
    private javax.swing.JButton cmdHelpNewReport;
    private javax.swing.JButton cmdNextNewReport;
    private javax.swing.JButton cmdSearchVehicleInfoNewReport;
    private org.jdesktop.swingx.JXImageView imgVehicleOwnerPhotoNewReport;
    private org.jdesktop.swingx.JXImageView imgVehiclePhotoNewReport;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel152;
    private javax.swing.JLabel jLabel153;
    private javax.swing.JLabel jLabel154;
    private javax.swing.JLabel jLabel155;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    private org.jdesktop.swingx.JXTitledPanel jXTitledPanel1;
    private javax.swing.JLabel lblVehicleEngineNoNewReport;
    private javax.swing.JLabel lblVehicleIMEINewReport;
    private javax.swing.JLabel lblVehicleModelNewReport;
    private javax.swing.JLabel lblVehicleNameNewReport;
    private javax.swing.JLabel lblVehicleOwnerNewReport;
    private javax.swing.JLabel lblVehicleStatusNewReport;
    private javax.swing.JPanel pnlAssaultReport;
    private javax.swing.JPanel pnlEquipmentTheftReport;
    private javax.swing.JPanel pnlMissingPersonReport;
    private javax.swing.JPanel pnlMoneyTheftReport;
    private javax.swing.JPanel pnlMurderReport;
    private javax.swing.JPanel pnlNewReport;
    private javax.swing.JPanel pnlReportCategory;
    private javax.swing.JPanel pnlTheftReport;
    private javax.swing.JPanel pnlThreatReport;
    private javax.swing.JPanel pnlVehicleTheft;
    private javax.swing.JTextArea txaIncidenceLocationNewReport;
    private javax.swing.JTextArea txaVhicleTheftDetailsNewReport;
    private javax.swing.JTextField txtReporterAgeNewReport;
    private javax.swing.JTextField txtReporterFirstNameNewReport;
    private javax.swing.JTextField txtReporterLastNameNewReport;
    private javax.swing.JTextField txtReporterPhoneNoNewReport;
    private javax.swing.JTextField txtVehiclePlateNoNewReport;
    // End of variables declaration//GEN-END:variables
}
