/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manager;

import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import manager.ui.model.WantedPersonTableModel;
import org.json.JSONObject;

/**
 *
 * @author user
 */
public class WantedPersonDialog extends javax.swing.JDialog {

    WantedPersonTableModel wantedPersonTableModel = new WantedPersonTableModel();

    /**
     * Creates new form WantedPersonDialog
     */
    public WantedPersonDialog(javax.swing.JFrame parent, boolean modal) {

        super(parent, modal);
        initComponents();

        this.addWindowListener(new WindowAdapter() {

            @Override
            public void windowOpened(WindowEvent e) {
                Object[] obj_states = ServerManager.mapStatesAndLGAs.keySet().toArray();
                Arrays.sort(obj_states);

                if (cboWantedPersonState.getItemCount() != obj_states.length) {
                    cboWantedPersonState.removeAllItems();//clear previous
                    for (Object obj_state : obj_states) {
                        cboWantedPersonState.addItem(obj_state);
                    }
                }

            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel16 = new javax.swing.JPanel();
        cboWantedPersonState = new javax.swing.JComboBox();
        jLabel215 = new javax.swing.JLabel();
        jLabel214 = new javax.swing.JLabel();
        cboWantedPersonLGA = new javax.swing.JComboBox();
        cboWantedPersonSearch = new javax.swing.JButton();
        imgWantedPersonPhoto = new org.jdesktop.swingx.JXImageView();
        lblWantedPersonFullName = new javax.swing.JLabel();
        jScrollPane22 = new javax.swing.JScrollPane();
        tblWantedPerson = new manager.ui.WantedPersonTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Wanted Persons");
        setBounds(this.getCenteredBounds(0.8, 0.9));
        setPreferredSize(this.getFormDimension(0.8, 0.9));

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Filter by location - where the person was declared wanted", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana Ref", 0, 14))); // NOI18N

        cboWantedPersonState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboWantedPersonStateActionPerformed(evt);
            }
        });

        jLabel215.setText("State");

        jLabel214.setText("LGA");

        cboWantedPersonSearch.setText("Search");
        cboWantedPersonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboWantedPersonSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel215, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboWantedPersonState, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel214, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(cboWantedPersonLGA, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(cboWantedPersonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel215)
                    .addComponent(jLabel214))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboWantedPersonState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboWantedPersonLGA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboWantedPersonSearch))
                .addContainerGap())
        );

        imgWantedPersonPhoto.setPreferredSize(new java.awt.Dimension(301, 278));

        javax.swing.GroupLayout imgWantedPersonPhotoLayout = new javax.swing.GroupLayout(imgWantedPersonPhoto);
        imgWantedPersonPhoto.setLayout(imgWantedPersonPhotoLayout);
        imgWantedPersonPhotoLayout.setHorizontalGroup(
            imgWantedPersonPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );
        imgWantedPersonPhotoLayout.setVerticalGroup(
            imgWantedPersonPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        lblWantedPersonFullName.setFont(new java.awt.Font("Vrinda", 1, 18)); // NOI18N

        tblWantedPerson.setModel(wantedPersonTableModel);
        tblWantedPerson.setRowHeight(122);
        tblWantedPerson.setSelectionModel(setWantedPersonSelectionModel());
        jScrollPane22.setViewportView(tblWantedPerson);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblWantedPersonFullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imgWantedPersonPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(20, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblWantedPersonFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(imgWantedPersonPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboWantedPersonStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboWantedPersonStateActionPerformed

        Object o_state = this.cboWantedPersonState.getSelectedItem();

        ArrayList lgas_list = ServerManager.mapStatesAndLGAs.get((String) o_state);

        this.cboWantedPersonLGA.removeAllItems();
        Object[] lgas = lgas_list.toArray();
        Arrays.sort(lgas);
        for (Object lga : lgas) {
            this.cboWantedPersonLGA.addItem(lga);
        }

    }//GEN-LAST:event_cboWantedPersonStateActionPerformed

    private void cboWantedPersonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboWantedPersonSearchActionPerformed

        String _state = cboWantedPersonState.getSelectedItem().toString();
        String _lga = cboWantedPersonLGA.getSelectedItem().toString();
        DBResource dBResource = null;

        try {

            String columns[] = new String[]{"SN",
                "FIRST_NAME",
                "SURNAME",
                "SEX",
                "DATE_OF_BIRTH",
                "PHONE_NO",
                "REASON_FOR_ARREST",//or reason for declaring wanted
                "STATUS_DATE",
                "PHOTO_FILE_NAME"};

            String condition = " WHERE STATE='" + _state + "'"
                    + "AND LGA='" + _lga + "'";

            dBResource = ServerManager.sendQueryAutoPolice("crime_case", columns, condition);

            ServerManager.wantedPersonTableModel.clearData();

            JSONObject json = new JSONObject();
            while (dBResource.rs.next()) {

                String photo_filename = dBResource.rs.getString("PHOTO_FILE_NAME");

                String fname = dBResource.rs.getString("FIRST_NAME");
                String lname = dBResource.rs.getString("SURNAME");
                String full_name = fname + " " + lname;
                json.put("", dBResource.rs.getInt("SN"));
                json.put("wanted_full_name", full_name);
                json.put("wanted_age", dBResource.rs.getString("DATE_OF_BIRTH"));
                json.put("wanted_sex", dBResource.rs.getString("SEX"));
                json.put("phone_no", dBResource.rs.getString("PHONE_NO"));
                json.put("reason_wanted", dBResource.rs.getString("REASON_FOR_ARREST"));
                json.put("date_declared_wanted", dBResource.rs.getString("STATUS_DATE"));
                json.put("wanted_photo_file_name", photo_filename);//important!!!

                ServerManager.wantedPersonTableModel.add(photo_filename, json.toString());
            }

        } catch (SQLException ex) {
            Logger.getLogger(ServerManager.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            if (dBResource != null) {
                dBResource.close();
            }
        }
    }//GEN-LAST:event_cboWantedPersonSearchActionPerformed
    ListSelectionModel setWantedPersonSelectionModel() {
        ListSelectionModel listSelectionModel = this.tblWantedPerson.getSelectionModel();
        listSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        listSelectionModel.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {

                //Display the image of the wanted person in the large image view
                int selected_row = e.getFirstIndex();
                String str_json = wantedPersonTableModel.getDetail(selected_row);
                JSONObject json = new JSONObject(str_json);
                String photo_file_name = json.getString("wanted_photo_file_name");

                ServerManager.imageLoader.loadImage(photo_file_name, imgWantedPersonPhoto);//load the image

                //display the wanted person full name
                String wanted_fullname = json.getString("wanted_full_name");
                lblWantedPersonFullName.setText(wanted_fullname);
            }
        });

        return listSelectionModel;
    }

    Rectangle getCenteredBounds(double percent_screen_width, double percent_screen_height) {
        int task_bar_height = 37;
        int screen_width = (int) this.getGraphicsConfiguration().getBounds().getWidth();
        int screen_height = (int) this.getGraphicsConfiguration().getBounds().getHeight();
        int w = (int) (percent_screen_width * screen_width);
        int h = (int) (percent_screen_height * screen_height);

        int x = (int) ((screen_width - w) / 2);
        int y = (int) ((screen_height - h) / 2);

        if (h + y > screen_height - task_bar_height) {
            y = 0;
            h = screen_height - task_bar_height;
        }
        return new Rectangle(x, y, w, h);
    }

    private Dimension getFormDimension(double percent_screen_width, double percent_screen_height) {

        int screen_width = (int) this.getGraphicsConfiguration().getBounds().getWidth();
        int screen_height = (int) this.getGraphicsConfiguration().getBounds().getHeight();
        int w = (int) (percent_screen_width * screen_width);
        int h = (int) (percent_screen_height * screen_height);

        return new Dimension(w, h);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WantedPersonDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WantedPersonDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WantedPersonDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WantedPersonDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WantedPersonDialog dialog = new WantedPersonDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox cboWantedPersonLGA;
    private javax.swing.JButton cboWantedPersonSearch;
    private javax.swing.JComboBox cboWantedPersonState;
    public org.jdesktop.swingx.JXImageView imgWantedPersonPhoto;
    private javax.swing.JLabel jLabel214;
    private javax.swing.JLabel jLabel215;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JLabel lblWantedPersonFullName;
    private manager.ui.WantedPersonTable tblWantedPerson;
    // End of variables declaration//GEN-END:variables
}
