package com.ukonect.www.util

object Constants {


    val KEY_APP_USER = "KEY_APP_USER"

    val WS_RETRY_BASE_DURATION: Long = 5000

    val WS_RETRY_MAX_DURATION: Long = 5000

    //onActivityResult Request code
    val GPS_REQUEST: Int = 1
    val PPROFIE_PHOTO_REQUEST: Int = 2

    val DEFAULT_SEARCH_LIMIT = 10
    val SMS_TYPE = "SMS_TYPE"
    val UPGRADE = "UPGRADE"
    val PHONE_NO = "PHONE_NO"
    val USER_ID = "USER_ID"
    var FREE_USERS = "FREE_USERS"
    var SILVER_USERS = "SILVER_USERS"
    var GOLD_USERS = "GOLD_USERS"

    val STR_NA: String = "N/A"

    val STR_AUTO_BACKUP_CONTACTS = "Auto Backup Contacts"
    val STR_FONT_SIZE = "Font Size"
    val STR_LOCATION_PROXIMITY = "Location Proximity"
    val STR_RECORD_CALLS = "Record Calls"
    val STR_FREE_USERS = "Free Users"
    val STR_SILVER_USERS = "Silver Users"
    val STR_GOLD_USERS = "Gold Users"
    val STR_NOTIFICATION = "Notifications"
    val STR_GEOSENSING = "Geosensing"

    var KEY_APP_USER_LAST_LOCATION = "KEY_APP_USER_LAST_LOCATION"

    val KEY_PROFILE_LOCATION_PROXIMITY_INDEX = "KEY_PROFILE_LOCATION_PROXIMITY_INDEX"
    val KEY_PROFILE_LOCATION_PROXIMITY_USERS = "KEY_PROFILE_LOCATION_PROXIMITY_USERS"
    val KEY_REMEBER_SEARCH_PROXIMITY_OPTION = "KEY_REMEBER_SEARCH_PROXIMITY_OPTION"
    val KEY_REMEBER_SEARCH_CATEGORY_OPTION ="KEY_REMEBER_SEARCH_CATEGORY_OPTION"

}