/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package naija.chess.ui;

import java.awt.Dimension;
import java.awt.Rectangle;
import java.util.Properties;
import naija.game.client.LocalUser;
import naija.game.client.Robot;
import naija.game.client.chess.Chess;
import naija.game.client.chess.board.ChessBoardPosition;

/**
 *
 * @author USER
 */
public class ChessFrame extends javax.swing.JFrame {

    /**
     * Creates new form ChessFrame
     */
    public ChessFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tlbToolBar = new javax.swing.JToolBar();
        tlgPlay = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        tlgLiveChess = new javax.swing.JToggleButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        tlgTournaments = new javax.swing.JToggleButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        tlgChessOpennings = new javax.swing.JToggleButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        pnlCenterPanel = new javax.swing.JPanel();
        pnlPlay = new javax.swing.JPanel();
        chessBoard2D = new naija.chess.ui.ChessBoard2D();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        pnlLiveChess = new javax.swing.JPanel();
        pnlTournaments = new javax.swing.JPanel();
        pnlChessOpennings = new javax.swing.JPanel();
        pnlChat = new javax.swing.JPanel();
        pnlStatusPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuNaijaChess = new javax.swing.JMenu();
        mnuContacts = new javax.swing.JMenu();
        mnuView = new javax.swing.JMenu();
        mnuTools = new javax.swing.JMenu();
        mnuHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NaijaChess - username goes here");
        setBounds(this.getCenteredBounds(0.8, 0.8));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        tlbToolBar.setBackground(new java.awt.Color(153, 153, 153));
        tlbToolBar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tlbToolBar.setRollover(true);
        tlbToolBar.setMaximumSize(new java.awt.Dimension(2000, 30));
        tlbToolBar.setPreferredSize(new java.awt.Dimension(100, 35));

        buttonGroup1.add(tlgPlay);
        tlgPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/naija/chess/images/test.png"))); // NOI18N
        tlgPlay.setText("My Game");
        tlgPlay.setFocusable(false);
        tlgPlay.setMaximumSize(new java.awt.Dimension(120, 100));
        tlgPlay.setPreferredSize(new java.awt.Dimension(80, 35));
        tlgPlay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbToolBar.add(tlgPlay);
        tlbToolBar.add(jSeparator1);

        buttonGroup1.add(tlgLiveChess);
        tlgLiveChess.setIcon(new javax.swing.ImageIcon(getClass().getResource("/naija/chess/images/test.png"))); // NOI18N
        tlgLiveChess.setText("Watch Live");
        tlgLiveChess.setFocusable(false);
        tlgLiveChess.setMaximumSize(new java.awt.Dimension(120, 100));
        tlgLiveChess.setPreferredSize(new java.awt.Dimension(80, 35));
        tlgLiveChess.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbToolBar.add(tlgLiveChess);
        tlbToolBar.add(jSeparator2);

        buttonGroup1.add(tlgTournaments);
        tlgTournaments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/naija/chess/images/test.png"))); // NOI18N
        tlgTournaments.setText("Tournaments");
        tlgTournaments.setFocusable(false);
        tlgTournaments.setMaximumSize(new java.awt.Dimension(120, 100));
        tlgTournaments.setPreferredSize(new java.awt.Dimension(80, 35));
        tlgTournaments.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbToolBar.add(tlgTournaments);
        tlbToolBar.add(jSeparator3);

        buttonGroup1.add(tlgChessOpennings);
        tlgChessOpennings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/naija/chess/images/test.png"))); // NOI18N
        tlgChessOpennings.setText("Chess Opennings");
        tlgChessOpennings.setFocusable(false);
        tlgChessOpennings.setMaximumSize(new java.awt.Dimension(120, 100));
        tlgChessOpennings.setPreferredSize(new java.awt.Dimension(80, 35));
        tlgChessOpennings.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbToolBar.add(tlgChessOpennings);
        tlbToolBar.add(jSeparator4);

        getContentPane().add(tlbToolBar);

        pnlCenterPanel.setBackground(new java.awt.Color(102, 102, 255));
        pnlCenterPanel.setLayout(new java.awt.CardLayout());

        chessBoard2D.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout chessBoard2DLayout = new javax.swing.GroupLayout(chessBoard2D);
        chessBoard2D.setLayout(chessBoard2DLayout);
        chessBoard2DLayout.setHorizontalGroup(
            chessBoard2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
        );
        chessBoard2DLayout.setVerticalGroup(
            chessBoard2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        jButton1.setText("animate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("from");

        jLabel2.setText("to");

        jButton2.setText("Test Start Chess");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Upward");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Downward");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPlayLayout = new javax.swing.GroupLayout(pnlPlay);
        pnlPlay.setLayout(pnlPlayLayout);
        pnlPlayLayout.setHorizontalGroup(
            pnlPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlayLayout.createSequentialGroup()
                .addComponent(chessBoard2D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPlayLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPlayLayout.createSequentialGroup()
                                .addGroup(pnlPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addGroup(pnlPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))))
                            .addComponent(jButton2)))
                    .addGroup(pnlPlayLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(pnlPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(jButton3))))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        pnlPlayLayout.setVerticalGroup(
            pnlPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chessBoard2D, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlPlayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPlayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(50, 50, 50)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCenterPanel.add(pnlPlay, "card2");

        javax.swing.GroupLayout pnlLiveChessLayout = new javax.swing.GroupLayout(pnlLiveChess);
        pnlLiveChess.setLayout(pnlLiveChessLayout);
        pnlLiveChessLayout.setHorizontalGroup(
            pnlLiveChessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );
        pnlLiveChessLayout.setVerticalGroup(
            pnlLiveChessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        pnlCenterPanel.add(pnlLiveChess, "card3");

        javax.swing.GroupLayout pnlTournamentsLayout = new javax.swing.GroupLayout(pnlTournaments);
        pnlTournaments.setLayout(pnlTournamentsLayout);
        pnlTournamentsLayout.setHorizontalGroup(
            pnlTournamentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );
        pnlTournamentsLayout.setVerticalGroup(
            pnlTournamentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        pnlCenterPanel.add(pnlTournaments, "card4");

        javax.swing.GroupLayout pnlChessOpenningsLayout = new javax.swing.GroupLayout(pnlChessOpennings);
        pnlChessOpennings.setLayout(pnlChessOpenningsLayout);
        pnlChessOpenningsLayout.setHorizontalGroup(
            pnlChessOpenningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );
        pnlChessOpenningsLayout.setVerticalGroup(
            pnlChessOpenningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        pnlCenterPanel.add(pnlChessOpennings, "card5");

        javax.swing.GroupLayout pnlChatLayout = new javax.swing.GroupLayout(pnlChat);
        pnlChat.setLayout(pnlChatLayout);
        pnlChatLayout.setHorizontalGroup(
            pnlChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );
        pnlChatLayout.setVerticalGroup(
            pnlChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        pnlCenterPanel.add(pnlChat, "card6");

        getContentPane().add(pnlCenterPanel);

        pnlStatusPanel.setBackground(new java.awt.Color(204, 204, 255));
        pnlStatusPanel.setMaximumSize(new java.awt.Dimension(32767, 30));
        pnlStatusPanel.setPreferredSize(new java.awt.Dimension(0, 25));

        javax.swing.GroupLayout pnlStatusPanelLayout = new javax.swing.GroupLayout(pnlStatusPanel);
        pnlStatusPanel.setLayout(pnlStatusPanelLayout);
        pnlStatusPanelLayout.setHorizontalGroup(
            pnlStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );
        pnlStatusPanelLayout.setVerticalGroup(
            pnlStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(pnlStatusPanel);

        jMenuBar1.setMinimumSize(new java.awt.Dimension(100, 20));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(225, 80));

        mnuNaijaChess.setText("NaijaChess");
        jMenuBar1.add(mnuNaijaChess);

        mnuContacts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/chess/pieces/alpha/60/wp.png"))); // NOI18N
        mnuContacts.setText("Contacts");
        mnuContacts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnuContacts.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mnuContacts.setIconTextGap(1);
        mnuContacts.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenuBar1.add(mnuContacts);

        mnuView.setText("View");
        jMenuBar1.add(mnuView);

        mnuTools.setText("Tools");
        jMenuBar1.add(mnuTools);

        mnuHelp.setText("Help");
        jMenuBar1.add(mnuHelp);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.chessBoard2D.animatePiece(Integer.parseInt(this.jTextField1.getText()), Integer.parseInt(this.jTextField2.getText()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String strFEN = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1";
        ChessBoardPosition boardPosition = new ChessBoardPosition(strFEN);
        
        Chess chess = new Chess.ChessBuilder( this.chessBoard2D)
                .whitePlayer(new LocalUser())
                .blackPlayer(new Robot("computer"))
                .setBoardPosition(boardPosition)
                .build();

        //chessBoard2D.initBoard(boardPosition);
        
     }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        chessBoard2D.setBoardOrientation(ChessBoard2D.WHITE_UPWARD);        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        chessBoard2D.setBoardOrientation(ChessBoard2D.WHITE_DOWNWARD);
    }//GEN-LAST:event_jButton4ActionPerformed

    private Rectangle getCenteredBounds(double percent_screen_width, double percent_screen_height) {
        int task_bar_height = 37;
        int screen_width = (int) this.getGraphicsConfiguration().getBounds().getWidth();
        int screen_height = (int) this.getGraphicsConfiguration().getBounds().getHeight();
        int w = (int) (percent_screen_width * screen_width);
        int h = (int) (percent_screen_height * screen_height);

        int x = (int) ((screen_width - w) / 2);
        int y = (int) ((screen_height - h) / 2);

        if (h + y > screen_height - task_bar_height) {
            y = 0;
            h = screen_height - task_bar_height;
        }
        
        return new Rectangle(x, y, w, h);
    }

    private Dimension getFormDimension(double percent_screen_width, double percent_screen_height) {

        int screen_width = (int) this.getGraphicsConfiguration().getBounds().getWidth();
        int screen_height = (int) this.getGraphicsConfiguration().getBounds().getHeight();
        int w = (int) (percent_screen_width * screen_width);
        int h = (int) (percent_screen_height * screen_height);

        return new Dimension(w, h);
    }

    private Rectangle getFormBounds() {
        System.out.println(this.getGraphicsConfiguration().getBounds().getWidth());
        int w = (int) (this.getGraphicsConfiguration().getBounds().getWidth());
        int h = (int) (this.getGraphicsConfiguration().getBounds().getHeight());
        System.out.println(w);
        return new Rectangle(0, 0, w, h);
    }

    private Dimension getFormDimension() {
        System.out.println(this.getGraphicsConfiguration().getBounds().getWidth());
        int w = (int) (this.getGraphicsConfiguration().getBounds().getWidth());
        int h = (int) (this.getGraphicsConfiguration().getBounds().getHeight());

        return new Dimension(w, h);
    }

    private static void setLookAndFeel() {

        try {
            /*
             To change the look and feel choose any of the
             classes below and instantiate using the setLookAndFeel
             method of the UIManager
            
             org.jvnet.substance.skin.SubstanceAutumnLookAndFeel
             org.jvnet.substance.skin.SubstanceBusinessBlackSteelLookAndFeel
             org.jvnet.substance.skin.SubstanceBusinessBlueSteelLookAndFeel
             org.jvnet.substance.skin.SubstanceBusinessLookAndFeel
             org.jvnet.substance.skin.SubstanceChallengerDeepLookAndFeel
             org.jvnet.substance.skin.SubstanceCremeCoffeeLookAndFeel
             org.jvnet.substance.skin.SubstanceCremeLookAndFeel
             org.jvnet.substance.skin.SubstanceEmeraldDuskLookAndFeel
             org.jvnet.substance.skin.SubstanceMagmaLookAndFeel
             org.jvnet.substance.skin.SubstanceMistAquaLookAndFeel
             org.jvnet.substance.skin.SubstanceMistSilverLookAndFeel
             org.jvnet.substance.skin.SubstanceModerateLookAndFeel
             org.jvnet.substance.skin.SubstanceNebulaBrickWallLookAndFeel
             org.jvnet.substance.skin.SubstanceNebulaLookAndFeel
             org.jvnet.substance.skin.SubstanceOfficeBlue2007LookAndFeel
             org.jvnet.substance.skin.SubstanceOfficeSilver2007LookAndFeel
             org.jvnet.substance.skin.SubstanceRavenGraphiteGlassLookAndFeel
             org.jvnet.substance.skin.SubstanceRavenGraphiteLookAndFeel
             org.jvnet.substance.skin.SubstanceRavenLookAndFeel
             org.jvnet.substance.skin.SubstanceSaharaLookAndFeel


             To change the look and feel choose any of the
             classes above and instantiate using the setLookAndFeel
             method of the UIManager
            
             BELOW ARE THE FEW ONES I LIKE
            
             org.jvnet.substance.skin.SubstanceMistAquaLookAndFeel
             org.jvnet.substance.skin.SubstanceBusinessLookAndFeel
             org.jvnet.substance.skin.SubstanceChallengerDeepLookAndFeel
             org.jvnet.substance.skin.SubstanceRavenLookAndFeel
             org.jvnet.substance.skin.SubstanceRavenGraphiteGlassLookAndFeel
            
            
            JTattoo
            
            com.jtattoo.plaf.acryl.AcrylLookAndFeel
            com.jtattoo.plaf.hifi.HiFiLookAndFeel
            
             */
            com.jtattoo.plaf.smart.SmartLookAndFeel.setTheme("Green", "", "");
            
            Properties props = new Properties();
            
            props.put("logoString", "");
            
            /*
            props.put("licenseKey", "");
            
            props.put("selectionBackgroundColor", "180 240 197"); 
            props.put("menuSelectionBackgroundColor", "180 240 197"); 
            
            props.put("controlColor", "218 254 230");
            props.put("controlColorLight", "218 254 230");
            props.put("controlColorDark", "180 240 197"); 

            props.put("buttonColor", "218 230 254");
            props.put("buttonColorLight", "255 255 255");
            props.put("buttonColorDark", "244 242 232");

            props.put("rolloverColor", "218 254 230"); 
            props.put("rolloverColorLight", "218 254 230"); 
            props.put("rolloverColorDark", "180 240 197"); 

            props.put("windowTitleForegroundColor", "0 0 0");
            props.put("windowTitleBackgroundColor", "180 240 197"); 
            props.put("windowTitleColorLight", "218 254 230"); 
            props.put("windowTitleColorDark", "180 240 197"); 
            props.put("windowBorderColor", "218 254 230");
            */
            javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChessFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChessFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChessFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChessFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                //Nimbus
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChessFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChessFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChessFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChessFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setLookAndFeel();
                new ChessFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private naija.chess.ui.ChessBoard2D chessBoard2D;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JMenu mnuContacts;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenu mnuNaijaChess;
    private javax.swing.JMenu mnuTools;
    private javax.swing.JMenu mnuView;
    private javax.swing.JPanel pnlCenterPanel;
    private javax.swing.JPanel pnlChat;
    private javax.swing.JPanel pnlChessOpennings;
    private javax.swing.JPanel pnlLiveChess;
    private javax.swing.JPanel pnlPlay;
    private javax.swing.JPanel pnlStatusPanel;
    private javax.swing.JPanel pnlTournaments;
    private javax.swing.JToolBar tlbToolBar;
    private javax.swing.JToggleButton tlgChessOpennings;
    private javax.swing.JToggleButton tlgLiveChess;
    private javax.swing.JToggleButton tlgPlay;
    private javax.swing.JToggleButton tlgTournaments;
    // End of variables declaration//GEN-END:variables
}
