/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.chuks.report.processor.factory;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.chuks.report.processor.*;
import com.chuks.report.processor.util.JDBCSettings;
import java.awt.Component;
import java.util.EventObject;
import javax.swing.DefaultListSelectionModel;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.CellEditorListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableCellEditor;

/**
 *
 * @author Chuks Alimele<chuksalimele at yahoo.com>
 */
public class TestTable extends javax.swing.JFrame {

    private TableProcessor t;

    /**
     * Creates new form TestTable
     */
    public TestTable() {
        initComponents();

        try {
            initProcessor();
        } catch (SQLException ex) {
            Logger.getLogger(TestTable.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void initProcessor() throws SQLException {
        JDBCSettings jdbcSettings = new JDBCSettings("jdbc:mysql://localhost:3306/autopolicedb", "autopolice", "autopolicepass", null);

        t = ProcessorFactory.getTableProcessor(jdbcSettings);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        cmdLoadOnTable1 = new javax.swing.JButton();
        cmdLoadOnTable2 = new javax.swing.JButton();
        cmdLoadOnTable3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jMoveTo15 = new com.chuks.report.processor.form.controls.JMoveTo();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        cmdLoadOnTable1.setText("Load on table 1");
        cmdLoadOnTable1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLoadOnTable1ActionPerformed(evt);
            }
        });
        getContentPane().add(cmdLoadOnTable1);

        cmdLoadOnTable2.setText("Load on table 2");
        cmdLoadOnTable2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLoadOnTable2ActionPerformed(evt);
            }
        });
        getContentPane().add(cmdLoadOnTable2);

        cmdLoadOnTable3.setText("Load on table 3");
        cmdLoadOnTable3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLoadOnTable3ActionPerformed(evt);
            }
        });
        getContentPane().add(cmdLoadOnTable3);

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jTextField1VetoableChange(evt);
            }
        });
        getContentPane().add(jTextField1);

        javax.swing.GroupLayout jMoveTo15Layout = new javax.swing.GroupLayout(jMoveTo15);
        jMoveTo15.setLayout(jMoveTo15Layout);
        jMoveTo15Layout.setHorizontalGroup(
            jMoveTo15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        jMoveTo15Layout.setVerticalGroup(
            jMoveTo15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
        );

        getContentPane().add(jMoveTo15);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("panel"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("panel2"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTabbedPane1.addTab("tab2", jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 111, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel3);

        getContentPane().add(jTabbedPane1);
        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdLoadOnTable1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLoadOnTable1ActionPerformed

        try {
            
            t.select()
                    .columns("ID", "CASH", "AMOUNT", "NAME", "AGE")
                    .from("test_table_1")
                    .where()
                    .lessOrEqual("AGE", "250")
                    .and()
                    .greaterOrEqual("AGE", "0");

            TableFieldSource s1 = new TableFieldSource("ADD");
            s1.addSources("id", "age");
            TableFieldSource s2 = new TableFieldSource("SUM");
            s2.addSources("cash", "amount");

            try {
                /*System.out.println(this.getContentPane());
                 if(true){
                 getContentPane().remove(jTable1);
                 getContentPane().revalidate();
                 getContentPane().repaint();
                 JTable tb = new JTable();
                 tb.setSize(100, 300);
                 getContentPane().add(tb);
                 getContentPane().repaint();
                 return;
                 }*/
                t.tableLoad(jTable1, new TableFieldCallBack() {
                    @Override
                    public Object onBeforeInput(TableFieldGen field, int row_index, int col_index) {
                        //System.out.println("row_index "+row_index+" col_index "+col_index);
                        if (field.fieldColumn().equalsIgnoreCase("sum")) {
                            double cash = Double.parseDouble(field.srcValue("cash").toString());
                            double amt = Double.parseDouble(field.srcValue("amount").toString());
                            return cash + amt;
                        }

                        if (field.fieldColumn().equalsIgnoreCase("add")) {
                            double id = Double.parseDouble(field.srcValue("id").toString());
                            double age = Double.parseDouble(field.srcValue("age").toString());
                            return id + age;
                        }
                        return field.srcValueAt(0);
                    }
                }, new UpdateTableHandler() {

                    @Override
                    public void doUpdate(ActionSQL a, TableFieldChange f) {
                        ITableField[] fd = f.getChanges();
                        
                    }

                }, new DeleteRowHandler() {

                    @Override
                    public void doDelete(ActionSQL a, RowSelection r) {
                        try {
                            for (int i = 0; i < r.count(); i++) {
                                
                                a.deleteFrom("test_table_1")
                                        .where()
                                        .equal("AGE", r.getValueAt(i, "ADD"))
                                        .executeDelete();
                                
                            }
                            a.close();
                        } catch (SQLException ex) {
                            Logger.getLogger(TestTable.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }, s1, s2);

                t.close();
                ListSelectionModel l = new DefaultListSelectionModel() ;
                l.addListSelectionListener(new ListSelectionListener() {

                    @Override
                    public void valueChanged(ListSelectionEvent e) {
                        //JTable table = (JTable) e.getSource();
                        int selected_row = jTable1.getSelectedRow();
                        if(selected_row==-1)
                            return;
                        System.out.println(selected_row);
                        System.out.println("t v at "+jTable1.getValueAt(selected_row, 0));
                        int m_r=jTable1.convertRowIndexToModel(selected_row);
                        int m_c=jTable1.convertColumnIndexToModel(0);
                        System.out.println("m v at "+jTable1.getModel().getValueAt(m_r, m_c));
                    }
                });
                jTable1.setSelectionModel(l);
                
            } catch (SQLException ex) {
                Logger.getLogger(TestTable.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TestTable.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmdLoadOnTable1ActionPerformed

    private void cmdLoadOnTable2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLoadOnTable2ActionPerformed


    }//GEN-LAST:event_cmdLoadOnTable2ActionPerformed

    private void cmdLoadOnTable3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLoadOnTable3ActionPerformed


    }//GEN-LAST:event_cmdLoadOnTable3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        System.out.println("jTextField1ActionPerformed");
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jTextField1VetoableChange
        System.out.println("jTextField1VetoableChange");
    }//GEN-LAST:event_jTextField1VetoableChange

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        System.out.println("jTextField1FocusLost");
    }//GEN-LAST:event_jTextField1FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                //Nimbus
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdLoadOnTable1;
    private javax.swing.JButton cmdLoadOnTable2;
    private javax.swing.JButton cmdLoadOnTable3;
    private javax.swing.JDialog jDialog1;
    private com.chuks.report.processor.form.controls.JMoveTo jMoveTo1;
    private com.chuks.report.processor.form.controls.JMoveTo jMoveTo10;
    private com.chuks.report.processor.form.controls.JMoveTo jMoveTo11;
    private com.chuks.report.processor.form.controls.JMoveTo jMoveTo12;
    private com.chuks.report.processor.form.controls.JMoveTo jMoveTo13;
    private com.chuks.report.processor.form.controls.JMoveTo jMoveTo14;
    private com.chuks.report.processor.form.controls.JMoveTo jMoveTo15;
    private com.chuks.report.processor.form.controls.JMoveTo jMoveTo2;
    private com.chuks.report.processor.form.controls.JMoveTo jMoveTo3;
    private com.chuks.report.processor.form.controls.JMoveTo jMoveTo4;
    private com.chuks.report.processor.form.controls.JMoveTo jMoveTo5;
    private com.chuks.report.processor.form.controls.JMoveTo jMoveTo6;
    private com.chuks.report.processor.form.controls.JMoveTo jMoveTo7;
    private com.chuks.report.processor.form.controls.JMoveTo jMoveTo8;
    private com.chuks.report.processor.form.controls.JMoveTo jMoveTo9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
